# -*- coding: utf-8 -*-
"""Copy_of_Support_Vector_Machine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UR88I6FyiY2b2rnAv42oDFdm4tmfbqQX

#Support Vector Machine (Supervised Machine Learning)
##Support Vector Machine is a supervised machine learning algorithm used primarily for:

**Classification (e.g., spam detection, image recognition)**

**Regression (SVR – Support Vector Regression)**
"""

from sklearn.datasets import load_digits
import pandas as pd
import matplotlib.pyplot as plt

"""##Load the dataset"""

digits = load_digits()

"""## Explore the Structure of the Digits Dataset

"""

dir(digits)

"""## View and Convert the Digits Dataset to a Pandas DataFrame for better visualization

"""

print(digits.data)
df1 = pd.DataFrame(digits.data)
df1

"""##Or you can do this"""

df = pd.DataFrame(digits.data, columns = digits.feature_names)

df

"""##Also append the target column to the dataframe"""

df["Target"] = digits.target

df

"""##Import essential libraries"""

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

"""## Define Features and Target, then Perform Train-Test Split

"""

X = df.drop('Target' , axis = 'columns')
y = df['Target']

#X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size = 0.2)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3)

"""## Train and Evaluate the Support Vector Classifier (SVC)

"""

model = SVC()
model.fit(X_train, y_train)

model.score(X_test, y_test)

result = model.predict(X_test)

result

"""##Plot the digits images to better visualize them"""

for i in range(20):
    plt.matshow(digits.images[result[i]])

"""## Excellent, now try changing the test size and train the model on Support Vector Classifier to identify how test and train size variation can increase/decrease model accuracy."""

#Start here

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# 1. Load the dataset and setup DataFrame
digits = load_digits()
df = pd.DataFrame(digits.data, columns=digits.feature_names)
df["Target"] = digits.target

X = df.drop("Target", axis="columns")
y = df["Target"]

# 2. Define the different test sizes you want to experiment with
# 0.1 means 10% test / 90% train, 0.5 means 50% test / 50% train
test_sizes = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

# Lists to store metrics for plotting
recorded_test_sizes = []
accuracies = []

print(f"{'Test Size':<12}{'Train Size':<12}{'Model Accuracy':<15}")
print("-" * 40)

# 3. Loop through each test size, train, and evaluate
for size in test_sizes:
    # random_state ensures a fair comparison across splits
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=size, random_state=42
    )

    # Initialize and fit the Support Vector Classifier
    model = SVC()
    model.fit(X_train, y_train)

    # Calculate accuracy score
    accuracy = model.score(X_test, y_test)

    # Store results
    recorded_test_sizes.append(size)
    accuracies.append(accuracy)

    # Print a clean summary table in the console
    train_size = 1.0 - size
    print(f"{size:<12.1f}{train_size:<12.1f}{accuracy * 100:<14.2f}%")

# 4. Generate a plot to visualize the trend
plt.figure(figsize=(8, 5))
plt.plot(
    recorded_test_sizes,
    accuracies,
    marker="o",
    color="b",
    linestyle="-",
    linewidth=2,
)
plt.title("Impact of Test Size Variation on SVC Accuracy")
plt.xlabel("Test Size (Ratio of Entire Dataset)")
plt.ylabel("Testing Accuracy Score")
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()