# -*- coding: utf-8 -*-
"""Copy_of_Decision_Tree_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkAYDjzLqyPhyPvln05qMI9o2oRyDKU-

#Decision Tree Classifier Lab

#Load essential libraries
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
from sklearn.model_selection import train_test_split

"""#Import the dataset"""

df = pd.read_csv("titanic.csv")
df

"""##Drop meaningless information"""

df = df.drop(columns = ['PassengerId','Name','SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis = 'columns')
df

"""##Data Preprocessing"""

import math
mean_age = df.Age.mean()
mean_age = math.floor(mean_age)
print(mean_age)

df['Age'] = df.Age.fillna(mean_age)
df

"""##Label Encode the non numeric features"""

LE_sex = LabelEncoder()
df['Sex'] = LE_sex.fit_transform(df['Sex'])

df

"""## Define Feature Matrix (X) and Target Vector (y)

"""

y = df['Survived']
X = df.drop('Survived', axis = 'columns')
X

"""## Train-Test Split and Model Initialization

"""

model = tree.DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4)

"""##Train the model"""

model.fit(X_train, y_train)

model.score(X_test, y_test)

"""##Predict results"""

model.predict(X_test)

y_test

"""##Try decision tree classifer on the same target column but this time use more feature columns than before."""

#Code here

import pandas as pd
import math
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
from sklearn.model_selection import train_test_split

# 1. Load the dataset
df = pd.read_csv("titanic.csv")

# 2. Drop only irrelevant features (Keeping SibSp, Parch, and Embarked this time)
df = df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], axis='columns')

# 3. Handle missing values for 'Age'
mean_age = math.floor(df.Age.mean())
df['Age'] = df.Age.fillna(mean_age)

# 4. Handle missing values for 'Embarked' (Fill with the most frequent value 'S')
df['Embarked'] = df.Embarked.fillna('S')

# 5. Encode Categorical Columns ('Sex' and 'Embarked') into numbers
le_sex = LabelEncoder()
df['Sex'] = le_sex.fit_transform(df['Sex'])

le_embarked = LabelEncoder()
df['Embarked'] = le_embarked.fit_transform(df['Embarked'])

# 6. Separate features (X) and target (y)
y = df['Survived']
X = df.drop('Survived', axis='columns')

# 7. Split the dataset (60% training, 40% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# 8. Initialize and train the Decision Tree Classifier
model = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=42)
model.fit(X_train, y_train)

# 9. Evaluate the model performance
accuracy = model.score(X_test, y_test)
predictions = model.predict(X_test)

# Print results
print(X.head())  # Verifying the newly added feature columns
print(f"\nModel Accuracy with more features: {accuracy * 100:.2f}%")