# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CgSC-OzbRxv7tRInchbzeLkZcCjEVRIs

#Import dependecies
"""

import pandas as pd
import numpy as np
from sklearn import linear_model

"""##Load the dataset"""

df = pd.read_csv("Cars_price.csv")

print(df.columns)

"""#Preprocessing"""

df.columns = df.columns.str.strip()
print(df.columns)

"""##Lets add a row"""

df.loc[5]=[3, 50000, None, 2100000]

df

df.describe()

"""##Handle missing data"""

mean_year = int(df['year'].mean())
df['year'] = df['year'].fillna(float(mean_year))
df

"""#Train the Model"""

reg = linear_model.LinearRegression()
reg.fit(df[['cylinders', 'milage', 'year']], df.price)

"""#Model Parameters"""

reg.coef_

reg.intercept_

reg.predict([[4, 30000, 2021]])

hiring = pd.read_csv("hiring.csv")
hiring

hiring['experience'].fillna(0, inplace=True)

hiring

import math

mean_test = hiring['test_score'].mean()
hiring['test_score'] = hiring.test_score.fillna(math.floor(mean_test))
hiring

reg_hiring = linear_model.LinearRegression()
reg.fit(hiring[['experience', 'test_score','interview_score']], hiring.salary)

reg.predict([[2, 9, 6],[12, 10, 10]])

import pickle

with open('car_pred_model','wb')as file:
    pickle.dump(reg, file)

with open('car_pred_model','rb') as file:
    mp = pickle.load(file)

mp.predict([[2,9,6]])

"""#Doing another with a different file which has car models in it."""

cars = pd.read_csv('carprices.csv')

cars

cars.columns = ['Car_Model', 'Milage', 'Sell_Price', 'Age']
cars

"""##One‑hot encode the Car_Model column to convert into numerical data for traininng the model.

The model can only be trained on numerical data
"""

dummies = pd.get_dummies(cars.Car_Model)
dummies

dum_cars = pd.concat([cars,dummies], axis = 'columns')
dum_cars

dum_cars.rename(columns={'Mercedez Benz C class': 'Mercedes_C_class'}, inplace=True)

dum_cars

"""##Drop the contextual column"""

dum_cars = dum_cars.drop('Car_Model', axis='columns')

l_model = linear_model.LinearRegression()

y = cars.Sell_Price
print(y)
X = dum_cars.drop('Sell_Price', axis = 'columns')
X

"""#Now train this data on linear regression and predict price for 45000 milage,4 years old Mercedes C class and 86000 milage, 7 years old Audi A5"""

#Code here

import pandas as pd
from sklearn import linear_model

# 1. Load data and clean columns
cars = pd.read_csv('carprices.csv')
cars.columns = ['Car_Model', 'Milage', 'Sell_Price', 'Age']

# 2. One-Hot Encoding for Car Model
dummies = pd.get_dummies(cars.Car_Model, dtype=int)
dum_cars = pd.concat([cars, dummies], axis='columns')

# 3. Clean column names and drop unnecessary features
dum_cars.rename(columns={'Mercedez Benz C class': 'Mercedes_C_class', 'Audi A5': 'Audi_A5', 'BMW X5': 'BMW_X5'}, inplace=True)
dum_cars = dum_cars.drop('Car_Model', axis='columns')

# 4. Define features (X) and target variable (y)
y = dum_cars['Sell_Price']
X = dum_cars.drop('Sell_Price', axis='columns')

# 5. Initialize and train the Linear Regression model
l_model = linear_model.LinearRegression()
l_model.fit(X, y)

# 6. Predict specific values
# Predict 1: 45000 mileage, 4 years old, Mercedes C class [Milage, Age, Audi_A5, BMW_X5, Mercedes_C_class]
pred_mercedes = l_model.predict([[45000, 4, 0, 0, 1]])

# Predict 2: 86000 mileage, 7 years old, Audi A5 [Milage, Age, Audi_A5, BMW_X5, Mercedes_C_class]
pred_audi = l_model.predict([[86000, 7, 1, 0, 0]])

# 7. Print results
print(f"Predicted Price for Mercedes C class: ${pred_mercedes[0]:.2f}")
print(f"Predicted Price for Audi A5: ${pred_audi[0]:.2f}")