# -*- coding: utf-8 -*-
"""Week_4_Day_3_Part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_VeCeYJ3fdZCfw8MLHp4hwqqi2fq87e3

**Note: Run servers on local instead of Colab**

Here are some comments for a tutorial on Model serialization with Pickle/Joblib:

1. **Introduction to Model Serialization**:
   - Model serialization is the process of converting a machine learning model into a format that can be easily saved and loaded. This is crucial for deploying models in production environments or sharing them with others
.

2. **Why Use Pickle or Joblib?**:
   - Pickle and Joblib are two popular libraries in Python for serializing machine learning models. Pickle is a built-in Python module that can serialize and deserialize any Python object, including custom classes and objects
.
   - Joblib is more efficient than Pickle when working with large numpy arrays, making it a better choice for serializing large machine learning models
.

3. **Security Considerations**:
   - Both Pickle and Joblib use the pickle protocol under the hood, which can execute arbitrary code during unpickling. Therefore, it is important to only load models from trusted sources to avoid security risks
.

4. **Saving a Model with Pickle**:
   - To save a model using Pickle, you can use the `pickle.dump` function. This function serializes the model and writes it to a file. For example:
     ```python
     import pickle
     with open('model.pkl', 'wb') as file:
         pickle.dump(model, file)
     ```
   - This code opens a file in write-binary mode and uses Pickle to serialize the model into this file
.

5. **Loading a Model with Pickle**:
   - To load a model using Pickle, you can use the `pickle.load` function. This function reads the serialized model from a file and deserializes it. For example:
     ```python
     with open('model.pkl', 'rb') as file:
         model = pickle.load(file)
     ```
   - This code opens the file in read-binary mode and uses Pickle to deserialize the model from this file
.

6. **Saving a Model with Joblib**:
   - To save a model using Joblib, you can use the `joblib.dump` function. This function serializes the model and writes it to a file. For example:
     ```python
     from joblib import dump, load
     dump(model, 'model.joblib')
     ```
   - This code uses Joblib to serialize the model into a file named 'model.joblib'
.

7. **Loading a Model with Joblib**:
   - To load a model using Joblib, you can use the `joblib.load` function. This function reads the serialized model from a file and deserializes it. For example:
     ```python
     model = load('model.joblib')
     ```
   - This code uses Joblib to deserialize the model from the file named 'model.joblib'
.

8. **Performance Comparison**:
   - Joblib is generally faster than Pickle when dealing with large numpy arrays due to its optimizations for such data structures. However, Pickle may be faster for smaller models or models that do not contain large numpy arrays
.

9. **Use Cases**:
   - Use Pickle when you need to serialize small models or models that do not contain large numpy arrays. Use Joblib when you need to serialize large models or models that contain large numpy arrays
.

10. **Conclusion**:
    - Both Pickle and Joblib are powerful tools for model serialization. The choice between them depends on the size of your model and the data structures it contains. Always ensure that you load models from trusted sources to avoid security risks
.
"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('clf', RandomForestClassifier(n_estimators=100, random_state=42))
])
pipeline.fit(X_train, y_train)

import pickle
version = '1.0.0'
filename_pkl = f'model_v{version}.pkl'
with open(filename_pkl, 'wb') as f:
    pickle.dump(pipeline, f)

import joblib
filename_joblib = f'model_v{version}.joblib'
joblib.dump(pipeline, filename_joblib)

with open(filename_pkl, 'rb') as f:
    model_pickle = pickle.load(f)
preds_pickle = model_pickle.predict(X_test)

with open(filename_pkl, 'rb') as f:
    model_pickle = pickle.load(f)
preds_pickle = model_pickle.predict(X_test)

model_joblib = joblib.load(filename_joblib)
preds_joblib = model_joblib.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, preds_pickle))
print(accuracy_score(y_test, preds_joblib))

import os
versions = ['1.0.0', '1.1.0', '2.0.0']
for v in versions:
    fname = f'model_v{v}.joblib'
    joblib.dump(pipeline, fname)
os.listdir('.')

import json
metadata = {
    'model_name': 'RandomForestPipeline',
    'versions': versions,
    'date_saved': {v: f'model_v{v}.joblib' for v in versions}
}
with open('model_metadata.json', 'w') as f:
    json.dump(metadata, f)

with open('model_metadata.json', 'r') as f:
    meta = json.load(f)
print(meta)





"""Excercise

### Overview  
This exercise guides you through training a scikit-learn pipeline, saving it with both Pickle and Joblib, managing model versions and metadata, and exposing the model via a simple Flask API  ([9. Model persistence — scikit-learn 1.6.1 documentation](https://scikit-learn.org/stable/model_persistence.html?utm_source=chatgpt.com)).  

### Tasks  
1. **Data Preparation:** Load the Breast Cancer Wisconsin dataset (`sklearn.datasets.load_breast_cancer`), split into train/test (80/20), and standardize features  ([Save and Load Machine Learning Models in Python with scikit-learn](https://machinelearningmastery.com/save-load-machine-learning-models-python-scikit-learn/?utm_source=chatgpt.com)).  
2. **Pipeline Construction:** Build an `sklearn.pipeline.Pipeline` with `StandardScaler` and `RandomForestClassifier(n_estimators=100, random_state=42)` and fit it on the training data  ([How to properly pickle sklearn pipeline when using custom ...](https://stackoverflow.com/questions/57888291/how-to-properly-pickle-sklearn-pipeline-when-using-custom-transformer?utm_source=chatgpt.com)).  
3. **Serialization:**  
   - Save the fitted pipeline using Pickle protocol 5 to `model_v1.pkl`.  
   - Save the same pipeline using Joblib to `model_v1.joblib`  ([Save Machine Learning Model Using Pickle and Joblib](https://www.analyticsvidhya.com/blog/2021/08/quick-hacks-to-save-machine-learning-model-using-pickle-and-joblib/?utm_source=chatgpt.com)).  
4. **Version Control:** Simulate versioning by retraining the pipeline with a different random seed, then saving as `model_v2.pkl`/`.joblib`; repeat for a third version. Create a `model_metadata.json` cataloging versions, file names, and timestamps  ([Machine Learning Model Serialization - Christopher Flynn](https://flynn.gg/blog/machine-learning-model-serialization/?utm_source=chatgpt.com)).  
5. **Deserialization & Validation:**  
   - Load each Pickle and Joblib file, run `.predict()` on the test set, and report accuracy.  
   - Measure and compare file sizes and load times between Pickle and Joblib  ([Pickle is over 10 times faster than joblib for save and load scikit ...](https://www.reddit.com/r/Python/comments/ypj13g/pickle_is_over_10_times_faster_than_joblib_for/?utm_source=chatgpt.com)).  
6. **Model Serving (Bonus):**  
   - Implement a minimal Flask app with two endpoints:  
     - `GET /models` returns available version metadata.  
     - `POST /predict` accepts JSON feature vectors and returns predicted classes using the latest model.  
   - Demonstrate sending requests via `requests` in Colab  ([Model Serialization using pickle and joblib - Kaggle](https://www.kaggle.com/code/tasnimniger/model-serialization-using-pickle-and-joblib?utm_source=chatgpt.com)).  

### Deliverables  
- A Colab notebook containing all code cells above.  
- The saved model files (`.pkl`, `.joblib`) and `model_metadata.json`.  
- A brief report (markdown cell) comparing Pickle vs Joblib in speed and size.  
- (Optional) The Flask app code cell demonstrating model serving.
"""

import os
import time
import json
import pickle
import joblib
from datetime import datetime
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

# --- Task 1: Data Preparation ---
data = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    data.data, data.target, test_size=0.2, random_state=42
)

# Initialize structures
metadata_catalog = {"models": []}
random_seeds = [42, 101, 2026]
benchmark_results = {}

print("=== Starting Model Training & Dual Serialization ===")

# --- Tasks 2, 3, & 4: Pipeline Construction, Serialization, and Version Control ---
for i, seed in enumerate(random_seeds, 1):
    version_str = f"v{i}"

    # Task 2: Build pipeline configuration
    pipe = Pipeline([
        ('scaler', StandardScaler()),
        ('rf', RandomForestClassifier(n_estimators=100, random_state=seed))
    ])
    pipe.fit(X_train, y_train)

    # Define file names
    pkl_file = f"model_{version_str}.pkl"
    joblib_file = f"model_{version_str}.joblib"

    # Task 3 & 4: Save configurations using specific methods
    with open(pkl_file, "wb") as f:
        pickle.dump(pipe, f, protocol=5)  # Native serialization protocol 5
    joblib.dump(pipe, joblib_file)        # Optimized serialization

    # Evaluate performance
    accuracy = pipe.score(X_test, y_test)

    # Log metadata values
    model_entry = {
        "version": version_str,
        "pkl_filename": pkl_file,
        "joblib_filename": joblib_file,
        "algorithm": "RandomForestClassifier",
        "n_estimators": 100,
        "random_state": seed,
        "test_accuracy": round(accuracy, 4),
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    metadata_catalog["models"].append(model_entry)
    print(f"Processed Version {version_str} (Seed: {seed}) -> Accuracy: {accuracy:.4f}")

# Save Task 4 structured JSON file configuration
with open("model_metadata.json", "w") as jf:
    json.dump(metadata_catalog, jf, indent=4)

# --- Task 5: Deserialization & Performance Validation Metrics ---
print("\n=== Running Deserialization & Benchmarking ===")
for i in range(1, 4):
    v = f"v{i}"
    pkl_file = f"model_{v}.pkl"
    joblib_file = f"model_{v}.joblib"

    # Profile Pickle deserialization speed
    t0 = time.perf_counter()
    with open(pkl_file, "rb") as f:
        model_pkl = pickle.load(f)
    t1 = time.perf_counter()
    pkl_load_time = t1 - t0
    pkl_acc = model_pkl.score(X_test, y_test)

    # Profile Joblib deserialization speed
    t0 = time.perf_counter()
    model_jlb = joblib.load(joblib_file)
    t1 = time.perf_counter()
    jlb_load_time = t1 - t0
    jlb_acc = model_jlb.score(X_test, y_test)

    # Extract size footprints
    pkl_size = os.path.getsize(pkl_file) / 1024  # convert bytes to KB
    jlb_size = os.path.getsize(joblib_file) / 1024

    benchmark_results[v] = {
        "pkl_acc": pkl_acc, "jlb_acc": jlb_acc,
        "pkl_size_kb": pkl_size, "jlb_size_kb": jlb_size,
        "pkl_time_ms": pkl_load_time * 1000, "jlb_time_ms": jlb_load_time * 1000
    }

    print(f"\n[Version {v} Verification]")
    print(f"  • Pickle -> Size: {pkl_size:.2f} KB | Load Time: {pkl_load_time*1000:.3f} ms | Acc: {pkl_acc:.4f}")
    print(f"  • Joblib -> Size: {jlb_size:.2f} KB | Load Time: {jlb_load_time*1000:.3f} ms | Acc: {jlb_acc:.4f}")

# 📝 Serialization Performance Report: Pickle vs Joblib

Based on the execution results of Task 5, here is a comparative analysis:

### 1. File Size Footprint
* **Observation:** For small models or pipelines involving standard estimators (like Random Forest on low-dimensional data), both `Pickle (Protocol 5)` and `Joblib` produce highly comparable file sizes (usually around 200-300 KB).
* **Key Difference:** Joblib is optimized for large NumPy arrays. If our dataset or model coefficients grow massive, Joblib handles memory matrices more efficiently through internal compression techniques.

### 2. Deserialization & Load Time Speed
* **Observation:** `Pickle (with Protocol 5)` often shows slightly faster load times in milliseconds for smaller tree-based pipelines compared to Joblib.
* **Key Difference:** While Pickle might win by a few milliseconds on tiny models, Joblib performs significantly better in production when loading large models with multiple deep estimators because it uses memory-mapping under the hood.

### 3. Predictive Consistency
* Both serialization libraries successfully maintain the exact same mathematical properties of the pipeline. The accuracy scores (`pkl_acc` and `jlb_acc`) match perfectly for all model versions (`v1`, `v2`, and `v3`).v## 📝 Serialization Performance Report: Pickle vs Joblib

Based on the execution results of Task 5, here is a comparative analysis:

import threading
import requests
import time
import json
import numpy as np
from flask import Flask, jsonify, request

app = Flask(__name__)

# --- Mock Feature Vector for Testing ---
# Dataset has 30 features, creating a dummy list matching data shape
mock_features = [14.0] * 30

@app.route('/models', methods=['GET'])
def get_models():
    """Returns the parsed structure of metadata properties."""
    try:
        with open("model_metadata.json", "r") as f:
            meta_data = json.load(f)
        return jsonify(meta_data)
    except FileNotFoundError:
        return jsonify({"error": "model_metadata.json not found"}), 404

@app.route('/predict', methods=['POST'])
def predict():
    """Runs data predictions using the highest version iteration layer."""
    req_payload = request.get_json()
    if not req_payload or 'features' not in req_payload:
        return jsonify({"error": "Missing 'features' index in package payload"}), 400

    # Load latest deployed system (model_v3) safely using joblib
    try:
        import joblib
        latest_deployed_model = joblib.load("model_v3.joblib")

        input_vector = np.array(req_payload['features']).reshape(1, -1)
        predicted_class = latest_deployed_model.predict(input_vector)

        return jsonify({
            "status": "success",
            "engine_version": "v3",
            "predicted_class": int(predicted_class[0])
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# --- Secure Threading Configuration for Colab Sandbox ---
def run_api_server():
    # Binding to 0.0.0.0 ensures internal proxy channels don't block requests
    app.run(host="0.0.0.0", port=5000, debug=False, use_reloader=False)

# Safely kill old threads if running by assigning daemon=True
api_thread = threading.Thread(target=run_api_server)
api_thread.daemon = True
api_thread.start()

# Provide context buffer time (3 seconds) for local port allocation to settle
print("Starting Flask background engine, waiting for port allocation...")
time.sleep(3)

print("\n=== Simulating Endpoint API Network Actions via 'requests' ===")

# Explicit complete routing to local environment mapping
BASE_URL = "http://127.0.0.1:5000"

try:
    # Call GET Endpoint
    get_response = requests.get(f"{BASE_URL}/models").json()
    print(f"\n✔ GET /models output trace:\n{json.dumps(get_response, indent=2)}")

    # Call POST Endpoint with properly structured feature grid
    post_payload = {"features": mock_features}
    post_response = requests.post(f"{BASE_URL}/predict", json=post_payload).json()
    print(f"\n✔ POST /predict output trace:\n{json.dumps(post_response, indent=2)}")

except requests.exceptions.ConnectionError as ce:
    print(f"\n Network routing fail: {ce}")
    print("Tip: Run the cell once more to allow the background thread to release socket locks.")