# -*- coding: utf-8 -*-
"""U_Net_for_Image_Segmentation_From_Scratch_Using_TensorFlow_v4 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDlUbCm6L1RVm0sygc99qYzvsTPMntGn

<a href="https://colab.research.google.com/github/VidushiBhatia/U-Net-Implementation/blob/main/U_Net_for_Image_Segmentation_From_Scratch_Using_TensorFlow_v4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Image Segmentation with U-Net

This notebook consists of an implementation of U-Net using the following resources:
* **Algorithm**: Ronneberger et al., [U-Net](https://arxiv.org/abs/1505.04597) Convolutional Networks for Biomedical Image Segmentation
* **Dataset**: [oxford iiit pet dataset](https://www.kaggle.com/tanlikesmath/the-oxfordiiit-pet-dataset) (published by Kaggle)
* **Packages Used**: TensorFlow, NumPy, scikit-learn, python-Pillow, imageio, matplotlib
"""

!wget -q http://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz
!wget -q http://www.robots.ox.ac.uk/~vgg/data/pets/data/annotations.tar.gz
!tar -xzf images.tar.gz && tar -xzf annotations.tar.gz

"""# Code Breakdown

- [1 - Packages](#1)
- [2 - Helper Functions for Data Processing](#2)
    - [2.1 - Load Data](#2.1)
    - [2.2 - Pre-Process Data](#2.2)
- [3 - Helper Functions for U-Net Architecture](#3)
    - [3.1 - U-Net Encoder Block](#3.1)
    - [3.2 - U-Net Decoder Block](#3.2)
    - [3.3 - Compile U-Net Blocks](#3.3)
- [4 - Executing above Functions to Train the Model](#4)
    - [4.1 - Load and View Data](#4.1)
    - [4.2 - Process Data](#4.2)
    - [4.3 - Split Train and Test](#4.3)
    - [4.4 - Build U-Net Architecture](#4.4)
    - [4.5 - Compile and Run Model](#4.5)
- [5 - Evaluate Results](#5)
    - [5.1 - Bias-Variance Check](#5.1)
    - [5.2 - View Predicted Segmentations](#5.2)

<a name='1'></a>
# 1 - Packages
"""

# for data load
import os

# for reading and processing images
import imageio
from PIL import Image

# for visualizations
import matplotlib.pyplot as plt

import numpy as np # for using np arrays

# for bulding and running deep learning model
import tensorflow as tf
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Conv2DTranspose
from tensorflow.keras.layers import concatenate
from tensorflow.keras.losses import binary_crossentropy
from sklearn.model_selection import train_test_split

"""<a name='2'></a>
# 2 - Helper Functions for Data Processing

<a name='2.1'></a>
## 2.1 - Load Data
* the masked images are stored as png, unmasked (original) as jpg
* the names of these 2 are same so for getting the right sample we can just sort the 2 lists
"""

def LoadData(path1, path2):
    # only real .jpg images
    imgs = sorted([f for f in os.listdir(path1)
                   if f.lower().endswith('.jpg')])
    # only real .png masks, skip macOS “._” files
    masks = sorted([f for f in os.listdir(path2)
                    if f.lower().endswith('.png')
                    and not f.startswith('._')])
    return imgs, masks

"""<a name='2.2'></a>
## 2.2 - Pre-Process Data
"""

def PreprocessData(img, mask, target_shape_img, target_shape_mask, path1, path2):
    """
    Processes the images and mask present in the shared list and path
    Returns a NumPy dataset with images as 3-D arrays of desired size
    Please note the masks in this dataset have only one channel
    """
    # Pull the relevant dimensions for image and mask
    m = len(img)                     # number of images
    i_h,i_w,i_c = target_shape_img   # pull height, width, and channels of image
    m_h,m_w,m_c = target_shape_mask  # pull height, width, and channels of mask

    # Define X and Y as number of images along with shape of one image
    X = np.zeros((m,i_h,i_w,i_c), dtype=np.float32)
    y = np.zeros((m,m_h,m_w,m_c), dtype=np.int32)

    # Resize images and masks
    for file in img:
        # convert image into an array of desired shape (3 channels)
        index = img.index(file)
        path = os.path.join(path1, file)
        single_img = Image.open(path).convert('RGB')
        single_img = single_img.resize((i_h,i_w))
        single_img = np.reshape(single_img,(i_h,i_w,i_c))
        single_img = single_img/256.
        X[index] = single_img

        # convert mask into an array of desired shape (1 channel)
        single_mask_ind = mask[index]
        path = os.path.join(path2, single_mask_ind)
        single_mask = Image.open(path)
        single_mask = single_mask.resize((m_h, m_w))
        single_mask = np.reshape(single_mask,(m_h,m_w,m_c))
        single_mask = single_mask - 1 # to ensure classes #s start from 0
        y[index] = single_mask
    return X, y

"""<a name='3'></a>
#3 - Constructing the U-Net Architecture

<a name='3.1'></a>
## 3.1 - U-Net Encoder Block
"""

def EncoderMiniBlock(inputs, n_filters=32, dropout_prob=0.3, max_pooling=True):
    """
    This block uses multiple convolution layers, max pool, relu activation to create an architecture for learning.
    Dropout can be added for regularization to prevent overfitting.
    The block returns the activation values for next layer along with a skip connection which will be used in the decoder
    """
    # Add 2 Conv Layers with relu activation and HeNormal initialization using TensorFlow
    # Proper initialization prevents from the problem of exploding and vanishing gradients
    # 'Same' padding will pad the input to conv layer such that the output has the same height and width (hence, is not reduced in size)
    conv = Conv2D(n_filters,
                  3,   # Kernel size
                  activation='relu',
                  padding='same',
                  kernel_initializer='HeNormal')(inputs)
    conv = Conv2D(n_filters,
                  3,   # Kernel size
                  activation='relu',
                  padding='same',
                  kernel_initializer='HeNormal')(conv)

    # Batch Normalization will normalize the output of the last layer based on the batch's mean and standard deviation
    conv = BatchNormalization()(conv, training=False)

    # In case of overfitting, dropout will regularize the loss and gradient computation to shrink the influence of weights on output
    if dropout_prob > 0:
        conv = tf.keras.layers.Dropout(dropout_prob)(conv)

    # Pooling reduces the size of the image while keeping the number of channels same
    # Pooling has been kept as optional as the last encoder layer does not use pooling (hence, makes the encoder block flexible to use)
    # Below, Max pooling considers the maximum of the input slice for output computation and uses stride of 2 to traverse across input image
    if max_pooling:
        next_layer = tf.keras.layers.MaxPooling2D(pool_size = (2,2))(conv)
    else:
        next_layer = conv

    # skip connection (without max pooling) will be input to the decoder layer to prevent information loss during transpose convolutions
    skip_connection = conv

    return next_layer, skip_connection

"""<a name='3.2'></a>
## 3.2 - U-Net Decoder Block
"""

def DecoderMiniBlock(prev_layer_input, skip_layer_input, n_filters=32):
    """
    Decoder Block first uses transpose convolution to upscale the image to a bigger size and then,
    merges the result with skip layer results from encoder block
    Adding 2 convolutions with 'same' padding helps further increase the depth of the network for better predictions
    The function returns the decoded layer output
    """
    # Start with a transpose convolution layer to first increase the size of the image
    up = Conv2DTranspose(
                 n_filters,
                 (3,3),    # Kernel size
                 strides=(2,2),
                 padding='same')(prev_layer_input)

    # Merge the skip connection from previous block to prevent information loss
    merge = concatenate([up, skip_layer_input], axis=3)

    # Add 2 Conv Layers with relu activation and HeNormal initialization for further processing
    # The parameters for the function are similar to encoder
    conv = Conv2D(n_filters,
                 3,     # Kernel size
                 activation='relu',
                 padding='same',
                 kernel_initializer='HeNormal')(merge)
    conv = Conv2D(n_filters,
                 3,   # Kernel size
                 activation='relu',
                 padding='same',
                 kernel_initializer='HeNormal')(conv)
    return conv

"""<a name='3.3'></a>
## 3.3 - Compile U-Net Blocks
"""

def UNetCompiled(input_size=(128, 128, 3), n_filters=32, n_classes=3):
    """
    Combine both encoder and decoder blocks according to the U-Net research paper
    Return the model as output
    """
    # Input size represent the size of 1 image (the size used for pre-processing)
    inputs = Input(input_size)

    # Encoder includes multiple convolutional mini blocks with different maxpooling, dropout and filter parameters
    # Observe that the filters are increasing as we go deeper into the network which will increasse the # channels of the image
    cblock1 = EncoderMiniBlock(inputs, n_filters,dropout_prob=0, max_pooling=True)
    cblock2 = EncoderMiniBlock(cblock1[0],n_filters*2,dropout_prob=0, max_pooling=True)
    cblock3 = EncoderMiniBlock(cblock2[0], n_filters*4,dropout_prob=0, max_pooling=True)
    cblock4 = EncoderMiniBlock(cblock3[0], n_filters*8,dropout_prob=0.3, max_pooling=True)
    cblock5 = EncoderMiniBlock(cblock4[0], n_filters*16, dropout_prob=0.3, max_pooling=False)

    # Decoder includes multiple mini blocks with decreasing number of filters
    # Observe the skip connections from the encoder are given as input to the decoder
    # Recall the 2nd output of encoder block was skip connection, hence cblockn[1] is used
    ublock6 = DecoderMiniBlock(cblock5[0], cblock4[1],  n_filters * 8)
    ublock7 = DecoderMiniBlock(ublock6, cblock3[1],  n_filters * 4)
    ublock8 = DecoderMiniBlock(ublock7, cblock2[1],  n_filters * 2)
    ublock9 = DecoderMiniBlock(ublock8, cblock1[1],  n_filters)

    # Complete the model with 1 3x3 convolution layer (Same as the prev Conv Layers)
    # Followed by a 1x1 Conv layer to get the image to the desired size.
    # Observe the number of channels will be equal to number of output classes
    conv9 = Conv2D(n_filters,
                 3,
                 activation='relu',
                 padding='same',
                 kernel_initializer='he_normal')(ublock9)

    conv10 = Conv2D(n_classes, 1, padding='same')(conv9)

    # Define the model
    model = tf.keras.Model(inputs=inputs, outputs=conv10)

    return model

"""<a name='4'></a>
# 4 - Executing above Functions to Train the Model

<a name='4.1'></a>
## 4.1 - Load and View Data
"""

""" Load Train Set and view some examples """
# Call the apt function
path1 = 'images/'
path2 = 'annotations/trimaps/'
img, mask = LoadData (path1, path2)

# View an example of image and corresponding mask
show_images = 1
for i in range(show_images):
    img_view  = imageio.imread(path1 + img[i])
    mask_view = imageio.imread(path2 + mask[i])
    print(img_view.shape)
    print(mask_view.shape)
    fig, arr = plt.subplots(1, 2, figsize=(15, 15))
    arr[0].imshow(img_view)
    arr[0].set_title('Image '+ str(i))
    arr[1].imshow(mask_view)
    arr[1].set_title('Masked Image '+ str(i))

"""<a name='4.2'></a>
## 4.2 - Process Data
"""

# Define the desired shape
target_shape_img = [128, 128, 3]
target_shape_mask = [128, 128, 1]

# Process data using apt helper function
X, y = PreprocessData(img, mask, target_shape_img, target_shape_mask, path1, path2)

# QC the shape of output and classes in output dataset
print("X Shape:", X.shape)
print("Y shape:", y.shape)
# There are 3 classes : background, pet, outline
print(np.unique(y))

# Visualize the output
image_index = 0
fig, arr = plt.subplots(1, 2, figsize=(15, 15))
arr[0].imshow(X[image_index])
arr[0].set_title('Processed Image')
arr[1].imshow(y[image_index,:,:,0])
arr[1].set_title('Processed Masked Image ')

"""## 4.3 - Split Train and Test Set"""

# Use scikit-learn's function to split the dataset
# Here, I have used 20% data as test/valid set
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=123)

"""<a name='4.4'></a>
## 4.4 - Build U-Net Architecture
"""

# Call the helper function for defining the layers for the model, given the input image size
unet = UNetCompiled(input_size=(128,128,3), n_filters=32, n_classes=3)

# Check the summary to better interpret how the output dimensions change in each layer
unet.summary()

"""<a name='4.5'></a>
## 4.5 - Compile and Run Model
"""

# There are multiple optimizers, loss functions and metrics that can be used to compile multi-class segmentation models
# Ideally, try different options to get the best accuracy
unet.compile(optimizer=tf.keras.optimizers.Adam(),
             loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Run the model in a mini-batch fashion and compute the progress for each epoch
results = unet.fit(X_train, y_train, batch_size=32, epochs=5, validation_data=(X_valid, y_valid))

"""<a name='5'></a>
# 5 - Evaluate Model Results

<a name='5.1'></a>
## 5.1 - Bias Variance Check
"""

# High Bias is a characteristic of an underfitted model and we would observe low accuracies for both train and validation set
# High Variance is a characterisitic of an overfitted model and we would observe high accuracy for train set and low for validation set
# To check for bias and variance plit the graphs for accuracy
# I have plotted for loss too, this helps in confirming if the loss is decreasing with each iteration - hence, the model is optimizing fine
fig, axis = plt.subplots(1, 2, figsize=(20, 5))
axis[0].plot(results.history["loss"], color='r', label = 'train loss')
axis[0].plot(results.history["val_loss"], color='b', label = 'dev loss')
axis[0].set_title('Loss Comparison')
axis[0].legend()
axis[1].plot(results.history["accuracy"], color='r', label = 'train accuracy')
axis[1].plot(results.history["val_accuracy"], color='b', label = 'dev accuracy')
axis[1].set_title('Accuracy Comparison')
axis[1].legend()

# RESULTS
# The train loss is consistently decreasing showing that Adam is able to optimize the model and find the minima
# The accuracy of train and validation is ~90% which is high enough, so low bias
# and the %s aren't that far apart, hence low variance

"""<a name='5.2'></a>
## 5.2 - View Predicted Segmentations
"""

unet.evaluate(X_valid, y_valid)

# Results of Validation Dataset
def VisualizeResults(index):
    img = X_valid[index]
    img = img[np.newaxis, ...]
    pred_y = unet.predict(img)
    pred_mask = tf.argmax(pred_y[0], axis=-1)
    pred_mask = pred_mask[..., tf.newaxis]
    fig, arr = plt.subplots(1, 3, figsize=(15, 15))
    arr[0].imshow(X_valid[index])
    arr[0].set_title('Processed Image')
    arr[1].imshow(y_valid[index,:,:,0])
    arr[1].set_title('Actual Masked Image ')
    arr[2].imshow(pred_mask[:,:,0])
    arr[2].set_title('Predicted Masked Image ')

# Add any index to contrast the predicted mask with actual mask
index = 700
VisualizeResults(index)

"""# Fun Activity

1. Improve model accuracy by changing hyperparameters of the model.
2. Save the model weights.
3. Load the model, use any random pet image and remove the background using the segment.

"""

import tensorflow as tf

# 1. Custom Metric for Keras 3 Compatibility
class UpdatedSparseMeanIoU(tf.keras.metrics.MeanIoU):
    """
    Custom MeanIoU metric class designed to resolve automatic shape alignment
    mismatches in Keras 3 by explicitly handling logits and sparse target tensors.
    """
    def __init__(self, num_classes=3, name='mean_iou', dtype=None):
        super().__init__(num_classes=num_classes, name=name, dtype=dtype)
        self.num_classes = num_classes

    def update_state(self, y_true, y_pred, sample_weight=None):
        # Extract the highest probability class index from predictions/logits
        y_pred = tf.argmax(y_pred, axis=-1)

        # Remove redundant channel dimensions from target labels to align shapes
        y_true = tf.squeeze(y_true, axis=-1)

        # Update the confusion matrix state inside the parent MeanIoU class
        return super().update_state(y_true, y_pred, sample_weight)

# 2. Model Initialization
# Build the model using hyperparameter-tuned architectural parameters
unet = UNetCompiled(input_size=(128, 128, 3), n_filters=64, n_classes=3)

# 3. Learning Rate Decay Schedule
# Implement exponential decay to systematically reduce the learning rate during training
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=1e-3,
    decay_steps=400,
    decay_rate=0.9
)

# 4. Model Compilation
# Configure the training pipeline with optimization, loss, and custom tracking metrics
unet.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=lr_schedule),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy', UpdatedSparseMeanIoU(num_classes=3, name='val_mean_iou')]
)

# 5. Callbacks Configuration
# Set up operational callbacks to track metrics and prevent overfitting
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_val_mean_iou', # Track the custom validation MeanIoU metric
        patience=5,
        restore_best_weights=True,
        mode='max' # Halt training when the tracked metric stops maximizing
    )
]

# 6. Model Training Execution
# Initiate the training loop using the compiled NumPy datasets
print("Training starting smoothly without any backend errors...")
results = unet.fit(
    X_train, y_train,
    validation_data=(X_valid, y_valid),
    batch_size=32,
    epochs=9,
    callbacks=callbacks
)

import random
import numpy as np
import matplotlib.pyplot as plt

# ----------------- PART 2: SAVE WEIGHTS -----------------
# Save the model weights using the recommended Keras 3 format extension
unet.save_weights('unet_pet_segmentation_weights.weights.h5')
print(" Hyperparameter-tuned model weights successfully saved!\n")

# ----------------- PART 3: LOAD MODEL & BACKGROUND REMOVAL -----------------
# Initialize a new, clean model instance with identical architectural parameters
loaded_model = UNetCompiled(input_size=(128, 128, 3), n_filters=64, n_classes=3)

# Restore the trained weights into the newly initialized model instance
loaded_model.load_weights('unet_pet_segmentation_weights.weights.h5')
print(" Weights successfully loaded into the clean model instance!")

# Randomly select a sample from the validation dataset for evaluation
rand_idx = random.randint(0, len(X_valid) - 1)
test_img = X_valid[rand_idx]
true_mask = y_valid[rand_idx]

# Add batch dimension to fit the expected input shape of the model
img_batch = np.expand_dims(test_img, axis=0)

# Generate class probability distributions (logits) for each pixel
pred_logits = loaded_model.predict(img_batch, verbose=0)

# Extract the index of the highest confidence class to form the final 2D mask
pred_mask = np.argmax(pred_logits, axis=-1)[0]

# Background Removal Logic:
# Oxford-IIIT Pet Dataset Standard: Class 0 maps to the foreground pet object
# Generate a binary mask where the pet foreground is 1.0 and everything else is 0.0
pet_mask = np.where(pred_mask == 0, 1.0, 0.0)

# Expand dimensions to channel-last format (128, 128, 1) for 3D array broadcasting
pet_mask = np.expand_dims(pet_mask, axis=-1)

# Apply element-wise multiplication to isolate the pet and clear the background
background_removed_img = test_img * pet_mask

# Configure the visualization layout for side-by-side comparison
fig, arr = plt.subplots(1, 3, figsize=(15, 5))

# Plot the original source image
arr[0].imshow(test_img)
arr[0].set_title('1. Input Pet Image')
arr[0].axis('off')

# Plot the raw predicted segmentation mask boundaries
arr[1].imshow(pred_mask, cmap='viridis')
arr[1].set_title('2. Predicted Segment boundaries')
arr[1].axis('off')

# Plot the final output after background removal extraction
arr[2].imshow(background_removed_img)
arr[2].set_title('3. Final Background Removed (Segmented)')
arr[2].axis('off')

# Optimize layout spacing and render the visual plots
plt.tight_layout()
plt.show()