# -*- coding: utf-8 -*-
"""cnn_architectures_vgg_resnet_inception_tl (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WoK5bPlDSZAigDVJCpjcK3qLBEz62n8d

##Generate your kaggle token from profile and upload the json file in the cell below
"""

from google.colab import files
files.upload()  # Upload kaggle.json here

"""##Create a directory for kaggle datasets"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""##Download the flowers dataset"""

!kaggle datasets download -d alxmamaev/flowers-recognition
!unzip flowers-recognition.zip -d flowers/

"""## CNN Architectures : VGG, Resnet, InceptionNet, XceptionNet

### UseCases : Image Feature Extraction + Transfer Learning


<br>

A Gold mine dataset for comuter vision is the ImageNet dataset. It consists of about 14 M hand-labelled annotated images which contains over 22,000 day-to-day categories. Every year ImageNet competition is hosted in which the smaller version of this dataset (with 1000 categories) is used with an aim to accurately classify the images. Many winning solutions of the ImageNet Challenge have used state of the art convolutional neural network architectures to beat the best possible accuracy thresholds. In this kernel, I have discussed these popular architectures such as VGG16, 19, ResNet, AlexNet etc. In the end, I have explained how to generate image features using pretrained models and use them in machine learning models.

## Contents

<br>

From the high level perspective, I have discussed three main components

<ul>
    <li>1. CNN Architectures   </li>
<ul>
    <li>1. 1 VGG16</li>
    <li>1.2 VGG19 </li>
    <li>1.3 InceptionNet</li>
    <li>1.4 Resnet </li>
    <li>1.5 XceptionNet</li>
</ul>
    <li>2. Image Feature Extraction  </li>
    <li>3. Transfer Learning  </li>
</ul>


## 1. CNN Architectures
## 1.1 &nbsp;&nbsp; VGG16

VGG16 was publised in 2014 and is one of the simplest (among the other cnn architectures used in Imagenet competition). It's Key Characteristics are:   

1. This network contains total 16 layers in which weights and bias parameters are learnt.    
2. A total of 13 convolutional layers are stacked one after the other and 3 dense layers for classification.     
3. The number of filters in the convolution layers follow an increasing pattern (similar to decoder architecture of autoencoder).     
4. The informative features are obtained by max pooling layers applied at different steps in the architecture.    
5. The dense layers comprises of 4096, 4096, and 1000 nodes each.   
6. The cons of this architecture are that it is slow to train and produces the model with very large size.   

The VGG16 architecture is given below:

![](https://tech.showmax.com/2017/10/convnet-architectures/image_0-8fa3b810.png)

## Implementation : VGG16
Let's see how we can create this architecture using python's keras library. The following code block shows the implementation of VGG16 in keras.

"""

from keras.layers import Input, Conv2D, MaxPooling2D
from keras.layers import Dense, Flatten
from keras.models import Model

_input = Input((224,224,1))

conv1  = Conv2D(filters=64, kernel_size=(3,3), padding="same", activation="relu")(_input)
conv2  = Conv2D(filters=64, kernel_size=(3,3), padding="same", activation="relu")(conv1)
pool1  = MaxPooling2D((2, 2))(conv2)

conv3  = Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu")(pool1)
conv4  = Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu")(conv3)
pool2  = MaxPooling2D((2, 2))(conv4)

conv5  = Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu")(pool2)
conv6  = Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu")(conv5)
conv7  = Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu")(conv6)
pool3  = MaxPooling2D((2, 2))(conv7)

conv8  = Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu")(pool3)
conv9  = Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu")(conv8)
conv10 = Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu")(conv9)
pool4  = MaxPooling2D((2, 2))(conv10)

conv11 = Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu")(pool4)
conv12 = Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu")(conv11)
conv13 = Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu")(conv12)
pool5  = MaxPooling2D((2, 2))(conv13)

flat   = Flatten()(pool5)
dense1 = Dense(4096, activation="relu")(flat)
dense2 = Dense(4096, activation="relu")(dense1)
output = Dense(1000, activation="softmax")(dense2)

vgg16_model  = Model(inputs=_input, outputs=output)

"""## PreTrained Model : VGG16



Keras library also provides the pre-trained model in which one can load the saved model weights, and use them for different purposes : transfer learning, image feature extraction, and object detection. We can load the model architecture given in the library, and then add all the weights to the respective layers.

Before using the pretrained models, lets write a few functions which will be used to make some predictions. First, load some images and preprocess them.
"""

from keras.applications.vgg16 import decode_predictions
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
import matplotlib.pyplot as plt
from PIL import Image
import seaborn as sns
import pandas as pd
import numpy as np
import os

img1 = "flowers/flowers/daisy/10172567486_2748826a8b.jpg"
img2 = "flowers/flowers/dandelion/13881700933_69a750d418_n.jpg"
img3 = "flowers/flowers/sunflower/1297092593_e573c0a3d6.jpg"
img4 = "flowers/flowers/tulip/11746367_d23a35b085_n.jpg"
imgs = [img1, img2, img3, img4]

def _load_image(img_path):
    img = image.load_img(img_path, target_size=(224, 224))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis=0)
    img = preprocess_input(img)
    return img

def _get_predictions(_model):
    f, ax = plt.subplots(1, 4)
    f.set_size_inches(80, 40)
    for i in range(4):
        ax[i].imshow(Image.open(imgs[i]).resize((200, 200), Image.Resampling.LANCZOS))
    plt.show()

    f, axes = plt.subplots(1, 4)
    f.set_size_inches(80, 20)
    for i,img_path in enumerate(imgs):
        img = _load_image(img_path)
        preds  = decode_predictions(_model.predict(img), top=3)[0]
        b = sns.barplot(y=[c[1] for c in preds], x=[c[2] for c in preds], color="gray", ax=axes[i])
        b.tick_params(labelsize=55)
        f.tight_layout()

"""Now, we can perform following steps :
1. import VGG16 architecture from keras.applications  
2. Add the saved weights to the architecture
3. Use model to perform predictions
"""

from keras.applications.vgg16 import VGG16
vgg16_model = VGG16(weights = 'imagenet')
_get_predictions(vgg16_model)

"""## 1.2 &nbsp;&nbsp; VGG19

VGG19 is a similar model architecure as VGG16 with three additional convolutional layers, it consists of a total of 16 Convolution layers and 3 dense layers.  Following is the architecture of VGG19 model. In VGG networks, the use of 3 x 3 convolutions with stride 1 gives an effective receptive filed equivalent to 7 * 7. This means there are fewer parameters to train.

![](https://cdn-images-1.medium.com/max/1600/1*cufAO77aeSWdShs3ba5ndg.jpeg)


"""

from keras.applications.vgg19 import VGG19
vgg19_model = VGG19(weights='imagenet')
_get_predictions(vgg19_model)

"""## 1.4 Resnets

Original Paper : https://arxiv.org/pdf/1512.03385.pdf

All the previous models used deep neural networks in which they stacked many convolution layers one after the other. It was learnt that deeper networks are performing better. However, it turned out that this is not really true. Following are the problems with deeper networks:

- Network becomes difficult to optimize  
- Vanishing / Exploding Gradeints  
- Degradation Problem ( accuracy first saturates and then degrades )  

### Skip Connections   

So to address these problems, authors of the resnet architecture came up with the idea of skip connections with the hypothesis that the deeper layers should be able to learn something as equal as shallower layers. A possible solution is copying the activations from shallower layers and setting additional layers to identity mapping.   These connections are enabled by skip connections which are shown in the following figure.

![](https://cdn-images-1.medium.com/max/987/1*pUyst_ciesOz_LUg0HocYg.png)

So the role of these connections is to perform identity function over the activation of shallower layer, which in-turn produces the same activation. This output is then added with the activation of the next layer. To enable these connections or essentially enable this addition operation, one need to ensure the same dimentions of convolutions through out the network, that's why resnets have same 3 by 3 convolutions throughout.

### Key Advantage

By using residual blocks in the network, one can construct networks of any depth with the hypothesis that new layers are actually helping to learn new underlying patterns in the input data. The authors of the paper were able to create the deep neural network architecture with 152 layers. The variants of Resnets such as resnet34, resnet50, resnet101 have produced the solutions with very high accuracy in Imagenet competitions.

### Why it works ?

Lets discuss why residual networks are successful and enables the addition of more and more layers without the key problems ie. without hurting the network performance.

Consider a plain neural network (A) without residual network as shown. So in the network (A) the input X is passed to this Neural Network (NN) to give the activation A1.

  <br>

![](https://i.imgur.com/9j8bKaY.png)

Now, consider a more deeper network (B) in which a residual block (with 2 extra layers and a skip connection) is added in the previous network. So now, the activation A1 is being passed to Residual Block which in turns gives new activation A3.

if there was no skip connection, then A3 was:

>  A3 = relu ( W2 . A2 + b2)              ..... (without skip connection)

where W2 and b2 are weights and bias associated with layer L2. But, with skip connection another term A1 will be passed to L2. So the equation of A3 will be modified as:

> A3 = relu ( W2 . A2 + b2 + A1)

If we use L2 regularization or the weight decay methods, they will force W2 and b2 to become close to zero. In the worst case, if these become zero, then

> A3 = relu (A1)   

because relu will output 0 for negative, A1 for positive and we know that A1 is previous activation from relu which is positive.

> A3 = A1

This means that Identitiy function is easy for residual blocks to learn. By addition of residual blocks, model complexity was not increased. As this is only copying the previous activation to the next layers. However this is only the worst case situation, but the it may turn out that these additional layers learns something useful. In that case, the network performance will improve.

Hence, adding the residual blocks / skip connections does not hurt the network performance but infact increases the chances that new layers will learn something useful.

Let's look at the usage using pre-trained resnet 50 model.
"""

from keras.applications.resnet50 import ResNet50
resnet_model = ResNet50(weights='imagenet')
_get_predictions(resnet_model)

"""## &nbsp;&nbsp; 1.3 InceptionNets

Also known as GoogleNet consists of total 22 layers and was the winning model of 2014 image net challenge.

- Inception modules are the fundamental block of InceptionNets. The key idea of inception module is to design good local network topology (network within a network)  
- These modules or blocks acts as the multi-level feature extractor in which convolutions of different sizes are obtained to create a diversified feature map
- The inception modules also consists of 1 x 1 convolution blocks whose role is to perform dimentionaltiy reduction.  
- By performing the 1x1 convolution, the inception block preserves the spatial dimentions but reduces the depth. So the overall network's dimentions are not increased exponentially.  
- Apart from the regular output layer, this network also consists of two auxillary classification outputs which are used to inject gradients at lower layers.  

<br><br>

The inception module is shown in the following figure:  

![](https://hackathonprojects.files.wordpress.com/2016/09/inception_implement.png?w=649&h=337)

The complete architecture is shown below:

![](https://cdn-images-1.medium.com/max/2000/1*uXfC5fcbDsL0TJG4T8PsVw.png)

<br>

### Pre-Trained Model : InceptionV3

##Inception V3 accepts a different input image shape, let's change that.
"""

from keras.applications.vgg16 import decode_predictions
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
import matplotlib.pyplot as plt
from PIL import Image
import seaborn as sns
import pandas as pd
import numpy as np
import os

img1 = "flowers/flowers/daisy/10172567486_2748826a8b.jpg"
img2 = "flowers/flowers/dandelion/13881700933_69a750d418_n.jpg"
img3 = "flowers/flowers/sunflower/1297092593_e573c0a3d6.jpg"
img4 = "flowers/flowers/tulip/11746367_d23a35b085_n.jpg"
imgs = [img1, img2, img3, img4]

def _load_image(img_path):
    img = image.load_img(img_path, target_size=(299, 299))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis=0)
    img = preprocess_input(img)
    return img

def _get_predictions(_model):
    f, ax = plt.subplots(1, 4)
    f.set_size_inches(80, 40)
    for i in range(4):
        ax[i].imshow(Image.open(imgs[i]).resize((200, 200), Image.Resampling.LANCZOS))
    plt.show()

    f, axes = plt.subplots(1, 4)
    f.set_size_inches(80, 20)
    for i,img_path in enumerate(imgs):
        img = _load_image(img_path)
        preds  = decode_predictions(_model.predict(img), top=3)[0]
        b = sns.barplot(y=[c[1] for c in preds], x=[c[2] for c in preds], color="gray", ax=axes[i])
        b.tick_params(labelsize=55)
        f.tight_layout()

from keras.applications.inception_v3 import InceptionV3
inception_model = InceptionV3(weights='imagenet')
_get_predictions(inception_model)

"""#Activity

##Your task is to define the model architecture for VGG19 model.
"""

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

def build_vgg19(input_shape=(224, 224, 3), num_classes=1000):
    model = Sequential(name="VGG19_Architecture")

    # --- BLOCK 1 ---
    # Input size: 224x224x3 | Output size: 224x224x64
    model.add(Conv2D(filters=64, kernel_size=(3, 3), padding='same', activation='relu', input_shape=input_shape, name='block1_conv1'))
    model.add(Conv2D(filters=64, kernel_size=(3, 3), padding='same', activation='relu', name='block1_conv2'))
    # Max Pooling size ko adha (112x112x64) kar degi
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name='block1_pool'))

    # --- BLOCK 2 ---
    # Output size: 112x112x128
    model.add(Conv2D(filters=128, kernel_size=(3, 3), padding='same', activation='relu', name='block2_conv1'))
    model.add(Conv2D(filters=128, kernel_size=(3, 3), padding='same', activation='relu', name='block2_conv2'))

    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name='block2_pool'))


    # Output size: 56x56x256
    model.add(Conv2D(filters=256, kernel_size=(3, 3), padding='same', activation='relu', name='block3_conv1'))
    model.add(Conv2D(filters=256, kernel_size=(3, 3), padding='same', activation='relu', name='block3_conv2'))
    model.add(Conv2D(filters=256, kernel_size=(3, 3), padding='same', activation='relu', name='block3_conv3'))
    model.add(Conv2D(filters=256, kernel_size=(3, 3), padding='same', activation='relu', name='block3_conv4'))

    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name='block3_pool'))

    # --- BLOCK 4 ---
    # Output size: 28x28x512
    model.add(Conv2D(filters=512, kernel_size=(3, 3), padding='same', activation='relu', name='block4_conv1'))
    model.add(Conv2D(filters=512, kernel_size=(3, 3), padding='same', activation='relu', name='block4_conv2'))
    model.add(Conv2D(filters=512, kernel_size=(3, 3), padding='same', activation='relu', name='block4_conv3'))
    model.add(Conv2D(filters=512, kernel_size=(3, 3), padding='same', activation='relu', name='block4_conv4'))
    # Max Pooling size ko adha (14x14x512) kar degi
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name='block4_pool'))

    # --- BLOCK 5 ---
    # Output size: 14x14x512
    model.add(Conv2D(filters=512, kernel_size=(3, 3), padding='same', activation='relu', name='block5_conv1'))
    model.add(Conv2D(filters=512, kernel_size=(3, 3), padding='same', activation='relu', name='block5_conv2'))
    model.add(Conv2D(filters=512, kernel_size=(3, 3), padding='same', activation='relu', name='block5_conv3'))
    model.add(Conv2D(filters=512, kernel_size=(3, 3), padding='same', activation='relu', name='block5_conv4'))

    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name='block5_pool'))


    model.add(Flatten(name='flatten'))

    model.add(Dense(units=4096, activation='relu', name='fc1'))
    model.add(Dense(units=4096, activation='relu', name='fc2'))


    model.add(Dense(units=num_classes, activation='softmax', name='predictions'))

    return model


vgg19_model = build_vgg19()


vgg19_model.summary()