# -*- coding: utf-8 -*-
"""GPU_Acceleration (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dVuj1xoXe0LIHRnXy3ioPTug5LM7Vu6s

#Introduction to GPU Acceleration
### 🔍 Why Use GPUs?

GPUs are optimized for large-scale parallel computation, making them ideal for matrix-heavy tasks in deep learning. In this lab, you'll compare training times and performance on CPU vs GPU and learn how to write GPU-efficient code.

##Check device availability

## TensorFlow
"""

import tensorflow as tf
print("Is GPU available?", tf.config.list_physical_devices('GPU'))

"""##PyTorch"""

import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

"""## 🚀 Moving Models and Data to GPU

To fully utilize the GPU, both the model and input data must be moved to the GPU device. This ensures the computation is performed on the GPU instead of the CPU.

Let's see how to do this in both TensorFlow and PyTorch.

##TensorFlow - Using GPU Automatically
"""

# TensorFlow uses GPU by default when available
import tensorflow as tf

with tf.device('/GPU:0'):  # or '/CPU:0' for CPU
    a = tf.random.normal([1000, 1000])
    b = tf.random.normal([1000, 1000])
    c = tf.matmul(a, b)
    print("Operation completed on:", c.device)

"""##PyTorch - Manual GPU Transfer"""

import torch

# Use 'cuda' if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Example tensor operation on GPU
a = torch.randn(1000, 1000).to(device)
b = torch.randn(1000, 1000).to(device)
c = torch.matmul(a, b)

print("Tensor 'c' is on device:", c.device)

"""##Measuring Training Time on CPU vs GPU

## ⏱️ Performance Benchmark: CPU vs GPU

We'll train a simple model on the MNIST dataset using both CPU and GPU. This will help us visualize the speedup provided by GPU acceleration.

Steps:
- Train on CPU and measure the time
- Train on GPU and measure the time
- Compare the difference

"""

#CPU

import time
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Data
transform = transforms.ToTensor()
train_data = datasets.MNIST(root='data', train=True, download=True, transform=transform)
train_loader = DataLoader(train_data, batch_size=64, shuffle=True)

# Model
class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(784, 256)
        self.fc2 = nn.Linear(256, 10)

    def forward(self, x):
        x = x.view(-1, 784)
        x = F.relu(self.fc1(x))
        return F.log_softmax(self.fc2(x), dim=1)

#GPU

import time
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Data
transform = transforms.ToTensor()
train_data = datasets.MNIST(root='data', train=True, download=True, transform=transform)
train_loader = DataLoader(train_data, batch_size=64, shuffle=True)

# Model
class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(784, 256)
        self.fc2 = nn.Linear(256, 10)

    def forward(self, x):
        x = x.view(-1, 784)
        x = F.relu(self.fc1(x))
        return F.log_softmax(self.fc2(x), dim=1)

"""##Train on CPU"""

# Train on CPU
def train_on_cpu():
    device = torch.device("cpu")
    model = SimpleModel().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.NLLLoss()

    start_time = time.time()
    for epoch in range(1):  # Short training
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            output = model(images)
            loss = criterion(output, labels)
            loss.backward()
            optimizer.step()
    end_time = time.time()
    print(f"✅ CPU training time: {end_time - start_time:.2f} sec")

train_on_cpu()

"""##Train on GPU
Change your runtine to T4 GPU and run the following code block
"""

# Train on GPU
def train_on_gpu():
    if not torch.cuda.is_available():
        print("🚫 CUDA not available on this system.")
        return

    device = torch.device("cuda")
    model = SimpleModel().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.NLLLoss()

    start_time = time.time()
    for epoch in range(1):  # Short training
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            output = model(images)
            loss = criterion(output, labels)
            loss.backward()
            optimizer.step()
    end_time = time.time()
    print(f"✅ GPU training time: {end_time - start_time:.2f} sec")

train_on_gpu()

"""I suppose we got lesser time for the gpu, it makes more difference on larger models that have more number of layers and filters, gpu speeds up the matrix multiplication due to the presence of numerous small cores.

**So here's an activity for you**
##Use tensorflow to train a model on the MNIST digits dataset on both gpu and cpu and examine which one works faster.

Use your custom number of layers and filters to experiment with the hyperparameters of the model.
"""

#Using CNN

import tensorflow as tf
import time

# 1. Check hardware availability
gpus = tf.config.list_physical_devices('GPU')
print(f"GPUs Detected: {len(gpus)}")

# 2. Load and normalize the MNIST dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Scale pixel values to [0, 1] and add the channel dimension for CNN
x_train = x_train[..., tf.newaxis].astype("float32") / 255.0
x_test = x_test[..., tf.newaxis].astype("float32") / 255.0

# 3. Build a heavy model with custom layers and filters to strain the processors
def build_custom_nn():
    model = tf.keras.models.Sequential([
        # Large initial filter count to trigger massive matrix operations
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(28, 28, 1)),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),

        # Deepening the network with 256 filters
        tf.keras.layers.Conv2D(256, (3, 3), activation='relu'),
        tf.keras.layers.Flatten(),

        # Dense classification layers
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    return model

# 4. Benchmarking function
def benchmark_device(device_string, epochs_count=3):
    print(f"\n--- Training on Device: {device_string} ---")
    with tf.device(device_string):
        model = build_custom_nn()
        model.compile(optimizer='adam',
                      loss='sparse_categorical_crossentropy',
                      metrics=['accuracy'])

        # Warm-up run to exclude initial TensorFlow graph compilation lag
        model.fit(x_train[:1000], y_train[:1000], epochs=1, batch_size=128, verbose=0)

        # Actual timed benchmark
        start_time = time.time()
        model.fit(x_train, y_train, epochs=epochs_count, batch_size=128, verbose=1)
        end_time = time.time()

        execution_time = end_time - start_time
        return execution_time

# 5. Execute comparative analysis
cpu_duration = benchmark_device('/CPU:0')

if gpus:
    gpu_duration = benchmark_device('/GPU:0')
    print(f"\nCPU time: {cpu_duration:.2f}s | GPU time: {gpu_duration:.2f}s")
else:
    print("\n[System Notice] No physical GPU detected on this machine.")
    print(f"CPU time: {cpu_duration:.2f}s. GPU comparison skipped (no GPU to benchmark).")

#USING NN

import time

# 1. Check hardware availability
gpus = tf.config.list_physical_devices('GPU')
print(f"GPUs Detected: {len(gpus)}")

# 2. Load and normalize the MNIST dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Scale pixel values to [0, 1] and add the channel dimension
x_train = x_train[..., tf.newaxis].astype("float32") / 255.0
x_test = x_test[..., tf.newaxis].astype("float32") / 255.0

# 3. Build a simple fully-connected (NN) model
def build_custom_nn():
    model = tf.keras.models.Sequential([
        # Flatten the 28x28x1 image into a 784-length vector
        tf.keras.layers.Flatten(input_shape=(28, 28, 1)),

        # Dense hidden layers
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(128, activation='relu'),

        # Output layer: 10 classes (digits 0-9)
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    return model

# 4. Benchmarking function
def benchmark_device(device_string, epochs_count=3):
    print(f"\n--- Training on Device: {device_string} ---")
    with tf.device(device_string):
        model = build_custom_nn()
        model.compile(optimizer='adam',
                      loss='sparse_categorical_crossentropy',
                      metrics=['accuracy'])

        # Warm-up run to exclude initial TensorFlow graph compilation lag
        model.fit(x_train[:1000], y_train[:1000], epochs=1, batch_size=128, verbose=0)

        # Actual timed benchmark
        start_time = time.time()
        model.fit(x_train, y_train, epochs=epochs_count, batch_size=128, verbose=1)
        end_time = time.time()

        execution_time = end_time - start_time
        return execution_time

# 5. Execute comparative analysis
cpu_duration = benchmark_device('/CPU:0')

if gpus:
    gpu_duration = benchmark_device('/GPU:0')
    print(f"\nCPU time: {cpu_duration:.2f}s | GPU time: {gpu_duration:.2f}s")
else:
    print("\n[System Notice] No physical GPU detected on this machine.")
    print(f"CPU time: {cpu_duration:.2f}s. GPU comparison skipped (no GPU to benchmark).")