# -*- coding: utf-8 -*-
"""Copy_of_K_Means(Iris).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XEeXs_n9urtDY9v-N2Bp1mWryQNGDng

#K-Means Clustering (Unsupervised Learning)
"""

import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
import pandas as pd

"""##Load dataset"""

iris = load_iris()

dir(iris)

iris.feature_names

"""##Convert to dataframe"""

df = pd.DataFrame(iris.data)
df

"""##Let's use two columns"""

df = df.drop([0,1],axis='columns')

df

plt.scatter(df[2], df[3] , color = 'red', marker = '+')
plt.xlabel('Patel length (cm)')
plt.ylabel('Patel width (cm)')
plt.show()

"""## 🔬 Scale a Single Feature Using MinMaxScaler

In this step, we apply `MinMaxScaler` to scale a specific feature of the dataset.

### 🧮 Why MinMaxScaler?
- It scales values **between 0 and 1** (or a custom range).
- Useful for algorithms that are sensitive to feature magnitude (e.g., KMeans, SVM, Neural Networks).

"""

s_length = MinMaxScaler()
s_length.fit(df[[2]])
df[2] = s_length.transform(df[[2]])

df

s_width = MinMaxScaler()
s_width.fit(df[[3]])
df[3] = s_width.transform(df[[3]])

df

model = KMeans(n_clusters=2)
y_predicted = model.fit_predict(df[[2,3]])

y_predicted

df['predicted'] = y_predicted

df

df1 = df[df['predicted']==0]
df2 = df[df['predicted']==1]

print(df1)
print(df2)

plt.scatter(df1[2], df1[3], color = 'red' , marker ='.')
plt.scatter(df2[2], df2[3], color = 'black' , marker ='+')
plt.show()

df = pd.DataFrame(iris.data)
df

length = len(df.columns)
length

"""## 📉 Calculate SSE for Different Cluster Counts (Elbow Method)

"""

sse =[]
for i in range(1,length+1):
    km = KMeans(n_clusters=i)
    km.fit(df)
    sse.append(km.inertia_)

print(sse)

"""## 🧠 What is the Elbow Method?

The **Elbow Method** is a popular technique used to determine the **optimal number of clusters (K)** for KMeans clustering.

### 📊 How It Works:
1. **KMeans** is applied to the data for a range of values of K (e.g., 1 to 10).
2. For each K, the **SSE (Sum of Squared Errors)** is computed, which represents the compactness of the clusters.
   - This is also called **inertia_** in scikit-learn's KMeans.
3. A line plot is made:  
   - **X-axis**: number of clusters (K)  
   - **Y-axis**: SSE value for each K

### 🎯 Interpretation:
- As the number of clusters increases, SSE naturally decreases.
- At some point, the **rate of decrease sharply slows down**—forming an “elbow” in the plot.
- The **K at this elbow point** is considered the optimal number of clusters because it balances **model complexity and clustering performance**.

The method helps avoid overfitting while achieving good grouping of the data.

"""

plt.plot(range(length),sse)
plt.scatter(range(length),sse, marker ='.')
plt.show()

"""##What did you identify from the elbow method? Use elbow method to identify the number of clusters and try applying K-Means on that number of clusters."""

#Code here

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler


iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df = df.drop(
    ["sepal length (cm)", "sepal width (cm)"], axis="columns"
)


scaler = MinMaxScaler()

df[["petal length (cm)", "petal width (cm)"]] = scaler.fit_transform(
    df[["petal length (cm)", "petal width (cm)"]]
)


sse = []
k_rng = range(1, 11)
for k in k_rng:
    km = KMeans(n_clusters=k, random_state=42)
    km.fit(df[["petal length (cm)", "petal width (cm)"]])
    sse.append(km.inertia_)


plt.figure(figsize=(6, 4))
plt.plot(k_rng, sse, marker="o", color="purple")
plt.title("Elbow Method Graph")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("SSE (Inertia)")
plt.grid(True, linestyle=":", alpha=0.6)
plt.show()


final_model = KMeans(n_clusters=3, random_state=42)
y_predicted = final_model.fit_predict(
    df[["petal length (cm)", "petal width (cm)"]]
)


df["cluster"] = y_predicted


df1 = df[df.cluster == 0]
df2 = df[df.cluster == 1]
df3 = df[df.cluster == 2]

plt.figure(figsize=(7, 5))

plt.scatter(
    df1["petal length (cm)"],
    df1["petal width (cm)"],
    color="green",
    marker="+",
    label="Group 1",
)
plt.scatter(
    df2["petal length (cm)"],
    df2["petal width (cm)"],
    color="red",
    marker="*",
    label="Group 2",
)
plt.scatter(
    df3["petal length (cm)"],
    df3["petal width (cm)"],
    color="black",
    marker="o",
    label="Group 3",
)


plt.scatter(
    final_model.cluster_centers_[:, 0],
    final_model.cluster_centers_[:, 1],
    color="yellow",
    marker="X",
    s=150,
    label="Centroids",
)

plt.xlabel("Petal Length (Scaled)")
plt.ylabel("Petal Width (Scaled)")
plt.title("Final KMeans Clustering with K=3")
plt.legend()
plt.show()