# -*- coding: utf-8 -*-
"""Copy_of_PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5HUDazdzkKv5hE0WoNQsW6NeQ6cad6K

#Principal Component Analysis (Dimentionality Reduction)
**Principal Component Analysis** is a dimensionality reduction technique used in data science and machine learning. It transforms a high-dimensional dataset into a lower-dimensional one by:

1. Identifying the principal components (directions of maximum variance)

2. Projecting the data onto these components

3. Preserving as much information (variance) as possible
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score

"""##Load dataset"""

df = pd.read_csv("Copy of heart.csv")
df

"""# 1st Way"""

s_dum = pd.get_dummies(df.Sex)
s_dum

dum_cp = pd.get_dummies(df.ChestPainType)
dum_cp

rest_dum = pd.get_dummies(df.RestingECG)
rest_dum

ex_dum = pd.get_dummies(df.ExerciseAngina)
ex_dum

st_dum = pd.get_dummies(df.ST_Slope)
st_dum

X = pd.concat([df['Age'],s_dum, dum_cp, df.loc[:,['RestingBP','Cholesterol','FastingBS']], rest_dum, df['MaxHR'], ex_dum, df['Oldpeak'], st_dum],axis=1)
X

y = df.HeartDisease
y

"""# Alternative Way"""

df.describe()

mean_bp = df.RestingBP.mean()
df['RestingBP'] = df['RestingBP'].replace(0, mean_bp)
df['Cholesterol'] = df['Cholesterol'].replace(0, df.Cholesterol.mean())
df['FastingBS'] = df['FastingBS'].replace(0, df.FastingBS.mean())
df

df[df.RestingBP==0]

df = pd.get_dummies(df)
df

X = df.drop('HeartDisease',axis='columns')
y = df.HeartDisease
print(X)
print(y)

"""# Train Test Split"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

"""# Before PCA"""

rf = cross_val_score(RandomForestClassifier(n_estimators=35),X_train, y_train)

print(rf)

lr = cross_val_score(LogisticRegression(max_iter=5000),X_train, y_train)

print(lr)

model = KNeighborsClassifier(n_neighbors=9)
model.fit(X_train, y_train)
model.score(X_test, y_test)

"""# After PCA

## Normalize the Feature Matrix (X) with Standard Scaling
"""

scalar = StandardScaler()
scaled_x = scalar.fit_transform(X)
scaled_x.shape

"""## Perform Dimensionality Reduction Using PCA (95% Variance Retained)

"""

pca = PCA(0.95)
x_pca = pca.fit_transform(scaled_x)
x_pca.shape

"""#Train test split"""

X_train, X_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.2)

"""##Train on KNN"""

model = KNeighborsClassifier(n_neighbors=9)
model.fit(X_train, y_train)
model.score(X_test, y_test)

"""##Random Forest"""

rf = cross_val_score(RandomForestClassifier(n_estimators=35),X_train, y_train)

print(rf)

"""##Logistic Regression"""

lr = cross_val_score(LogisticRegression(max_iter=150),X_train, y_train)

print(lr)

"""##Try retaining less variance using PCA and determine how it makes a difference."""

#Code here

scaler = StandardScaler()


X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)


model_bina_pca = LogisticRegression()
model_bina_pca.fit(X_train, y_train)


print("Bina PCA ke Columns ki tadad:", X_scaled.shape[1])
print("Bina PCA ke Accuracy:", model_bina_pca.score(X_test, y_test))

pca = PCA(n_components=0.80)


X_pca = pca.fit_transform(X_scaled)


print("PCA (80% Variance) ke baad naye columns:", X_pca.shape[1])

X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)


model_with_pca = LogisticRegression()
model_with_pca.fit(X_train_pca, y_train)


print("PCA ke saath Accuracy:", model_with_pca.score(X_test_pca, y_test))