# -*- coding: utf-8 -*-
"""Week_4_AutoML_(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184Np1ZYe0jgUuhMYQDXw9DX3HgXfrqRe

# AutoML Tutorial: H2O AutoML
> **Run this notebook in Google Colab or Jupyter to learn about automated machine learning (AutoML) using H2O AutoML.**

## 1. Introduction
Automated Machine Learning (AutoML) simplifies the end-to-end ML workflow by:
- **Feature preprocessing**
- **Model selection**
- **Hyperparameter optimization**
- **Ensembling**

In this tutorial, we'll focus solely on **H2O AutoML**, a scalable AutoML framework supporting both regression and classification.

At the end, you'll complete an exercise applying AutoML.

## 2. Setup & Installation
"""

!pip install --quiet jedi
!pip install --quiet h2o
!pip install --quiet 'thinc<8.3.6'

"""## Regression on California Housing

"""

import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

"""## 3. Regression Example: California Housing"""

import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import h2o
from h2o.automl import H2OAutoML
from sklearn.metrics import mean_squared_error, r2_score

# Initialize H2O
h2o.init(max_mem_size="2G", nthreads=-1)

import pandas as pd

# Load data from local CSV files
train_df = pd.read_csv('/content/sample_data/california_housing_train.csv')
test_df = pd.read_csv('/content/sample_data/california_housing_test.csv')

# Combine train and test data
data_df = pd.concat([train_df, test_df], ignore_index=True)

# Separate features (X) and target (y)
X = data_df.drop(columns=['median_house_value'])
y = data_df['median_house_value'].rename('target')

# Display the first few rows of X and y to confirm
print("Features (X) head:")
display(X.head())
print("Target (y) head:")
display(y.head())

# Create H2OFrame
df = h2o.H2OFrame(pd.concat([X, y], axis=1))

# Split into train/test
train, test = df.split_frame(ratios=[0.8], seed=42)

"""### 3.1 Run H2O AutoML for Regression"""

aml_reg = H2OAutoML(
    max_runtime_secs=300,
    max_models=20,
    seed=42,
    nfolds=5,
    project_name="california_regression"
)
aml_reg.train(x=X.columns.tolist(), y='target', training_frame=train)

# Show leaderboard
df_leader_reg = aml_reg.leaderboard.as_data_frame()
print(df_leader_reg.head())

# Evaluate on test
perf_reg = aml_reg.leader.model_performance(test)
print(f"H2O Regression R²: {perf_reg.r2():.4f}")
print(f"H2O Regression RMSE: {perf_reg.rmse():.4f}")

"""## 4. Classification Example: Breast Cancer Dataset"""

from sklearn.datasets import load_breast_cancer

# Load and prepare dataset
data_cls = load_breast_cancer(as_frame=True)
Xc = data_cls.data
yc = data_cls.target.rename('target')

df_cls = h2o.H2OFrame(pd.concat([Xc, yc], axis=1))
train_cls, test_cls = df_cls.split_frame(ratios=[0.7], seed=42)

"""### 4.1 Run H2O AutoML for Classification"""

aml_cls = H2OAutoML(
    max_runtime_secs=300,
    max_models=20,
    seed=42,
    nfolds=5,
    balance_classes=True,
    project_name="breast_cancer_classification"
)
aml_cls.train(x=Xc.columns.tolist(), y='target', training_frame=train_cls)

# Show leaderboard
df_leader_cls = aml_cls.leaderboard.as_data_frame()
print(df_leader_cls.head())

# Evaluate on test
perf_cls = aml_cls.leader.model_performance(test_cls)
print(f"H2O Classification: {perf_cls}")

"""MSE (Mean Squared Error):
- Measures the average squared difference between predicted and actual values. Lower values indicate better performance.


RMSE (Root Mean Squared Error):
- The square root of MSE, providing an error metric in the same units as the target variable. Lower values are better.


MAE (Mean Absolute Error):
-Measures the average absolute difference between predicted and actual values. Lower values indicate better performance.


RMSLE (Root Mean Squared Logarithmic Error):
- Similar to RMSE but uses the logarithm of the values, making it more robust to outliers. Lower values are better.


Mean Residual Deviance:
- Measures the goodness of fit of the model. Lower values indicate a better fit.


R² (Coefficient of Determination):
- Represents the proportion of variance explained by the model. Values closer to 1 indicate better performance.


Null Degrees of Freedom:
- The number of observations minus 1.


Residual Degrees of Freedom:
- The number of observations minus the number of parameters estimated.


Null Deviance:
- The deviance of the null model (model with no predictors).


Residual Deviance:
- The deviance of the fitted model. Lower values indicate a better fit.


AIC (Akaike Information Criterion):
- A measure of model quality, balancing goodness of fit and model complexity. Lower values indicate a better model.
"""



"""## 5. Interpreting Results
- **Leaderboard** displays model ranking by default metric.
- Use `model_performance` to compute custom metrics (RMSE, R², AUC, accuracy, etc.).
- Top models are automatically ensembled by H2O's Stacked Ensemble.

## 6. AutoML Best Practices
- **Set time and model limits** (`max_runtime_secs`, `max_models`) to control cost and runtime.
- **Use cross-validation** (`nfolds`) for robust performance estimates.
- **Balance classes** for imbalanced classification tasks.
- **Review variable importance** on the leader model: `aml.leader.varimp()`.
- **Save and deploy** the best model: `h2o.save_model(aml.leader, path='best_model')`.

## 7. Exercise: Custom Dataset AutoML

**Task:** Apply H2O AutoML to a custom dataset.

1. Load any tabular dataset (CSV or from `sklearn.datasets`).
2. Decide whether it's a regression or classification task.
3. Initialize H2O and convert to `H2OFrame`.
4. Split into appropriate train/test ratios.
5. Run `H2OAutoML` with:
   - `max_runtime_secs=300`
   - `max_models=15`
   - `nfolds=5`
   - `balance_classes=True` (if classification)
6. Display the leaderboard and evaluate on the test set using relevant metrics.
7. Save the leaderboard to a pandas DataFrame and export it as `leaderboard.csv`
"""

import h2o
from h2o.automl import H2OAutoML
import pandas as pd
from sklearn.datasets import load_wine

# 1. Load a tabular dataset from sklearn
# We are using the Wine recognition dataset (Multiclass Classification)
raw_data = load_wine(as_frame=True)
df = raw_data.frame

# 2. Define the task type and target column
# Target: 'target' (Classifies wine into 3 categories)
# Task: Classification
target_col = "target"
feature_cols = raw_data.feature_names

# 3. Initialize H2O and convert to H2OFrame
h2o.init()

# Convert pandas DataFrame to H2OFrame
hf = h2o.H2OFrame(df)

# IMPORTANT: Target must be a factor (categorical) for a classification task
hf[target_col] = hf[target_col].asfactor()

# 4. Split into train (80%) and test (20%) ratios
train_hf, test_hf = hf.split_frame(ratios=[0.8], seed=42)

# 5. Run H2OAutoML with specified constraints
aml = H2OAutoML(
    max_runtime_secs=300,
    max_models=15,
    nfolds=5,
    balance_classes=True,  # True because this is a classification task
    seed=42,
)

# Train the models
aml.train(x=feature_cols, y=target_col, training_frame=train_hf)

# 6. Display leaderboard and evaluate on the test set
print("\n--- AutoML Leaderboard ---")
leaderboard = aml.leaderboard
print(leaderboard.head(rows=leaderboard.nrows))

# Evaluate the best model on the test set
print("\n--- Test Set Evaluation ---")
best_model = aml.leader
performance = best_model.model_performance(test_data=test_hf)
print(performance)

# 7. Save leaderboard to a pandas DataFrame and export to CSV
leaderboard_df = leaderboard.as_data_frame()
leaderboard_df.to_csv("leaderboard.csv", index=False)

print("\n[SUCCESS] Leaderboard successfully exported to 'leaderboard.csv'")

