# -*- coding: utf-8 -*-
"""Week_3_Day_3_Assignment (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_Qj566crJj8oaraHWf9AIbwTGbM4VHb
"""

# Import essential libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Set aesthetics for visualizations
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette('viridis')
plt.rcParams['figure.figsize'] = (12, 8)

# Load sample dataset (Titanic dataset)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Display first few rows of the dataset
df.head()

# Check dataset information
df.info()

# Generate basic summary statistics
df.describe()

# Count missing values in each column
df.isnull().sum()

# Check unique values in categorical columns
for col in df.select_dtypes(include=['object']).columns:
    print(f"\nUnique values in {col}:")
    print(df[col].value_counts())

# Univariate Analysis - Summary Statistics
# Calculate statistical measures including skewness for numerical variables
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
stats_df = pd.DataFrame({
    'Mean': df[num_cols].mean(),
    'Median': df[num_cols].median(),
    'Std Dev': df[num_cols].std(),
    'Skewness': df[num_cols].skew(),
    'Kurtosis': df[num_cols].kurt()
})
stats_df.round(2)

# Univariate Analysis - Visualizations
# Distribution of age
plt.figure(figsize=(12, 6))

# Histogram with KDE
plt.subplot(1, 2, 1)
sns.histplot(df['Age'].dropna(), kde=True, color='teal')
plt.title('Age Distribution', fontsize=14)
plt.xlabel('Age', fontsize=12)

# Boxplot
plt.subplot(1, 2, 2)
sns.boxplot(y=df['Age'].dropna(), color='teal')
plt.title('Age Boxplot', fontsize=14)
plt.tight_layout()
plt.show()

# Distribution of fare
plt.figure(figsize=(12, 6))

# Histogram with KDE
plt.subplot(1, 2, 1)
sns.histplot(df['Fare'], kde=True, color='purple')
plt.title('Fare Distribution', fontsize=14)
plt.xlabel('Fare', fontsize=12)

# Boxplot
plt.subplot(1, 2, 2)
sns.boxplot(y=df['Fare'], color='purple')
plt.title('Fare Boxplot', fontsize=14)
plt.tight_layout()
plt.show()

# Categorical value counts with visualization
plt.figure(figsize=(15, 12))

# Passenger class distribution
plt.subplot(2, 2, 1)
sns.countplot(x='Pclass', data=df, palette='viridis')
plt.title('Passenger Class Distribution', fontsize=14)

# Gender distribution
plt.subplot(2, 2, 2)
sns.countplot(x='Sex', data=df, palette='viridis')
plt.title('Gender Distribution', fontsize=14)

# Embarked distribution
plt.subplot(2, 2, 3)
sns.countplot(x='Embarked', data=df, palette='viridis')
plt.title('Port of Embarkation', fontsize=14)

# Survival distribution
plt.subplot(2, 2, 4)
sns.countplot(x='Survived', data=df, palette='viridis')
plt.title('Survival Distribution', fontsize=14)
plt.xticks([0, 1], ['Not Survived', 'Survived'])

plt.tight_layout()
plt.show()

# Bivariate Analysis
# Age distribution by survival status
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
sns.histplot(data=df, x='Age', hue='Survived', multiple='stack', palette='viridis')
plt.title('Age Distribution by Survival', fontsize=14)

plt.subplot(1, 2, 2)
sns.boxplot(x='Survived', y='Age', data=df, palette='viridis')
plt.title('Age vs Survival', fontsize=14)
plt.xticks([0, 1], ['Not Survived', 'Survived'])

plt.tight_layout()
plt.show()

# Fare distribution by survival status
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
sns.histplot(data=df, x='Fare', hue='Survived', multiple='stack', palette='viridis')
plt.title('Fare Distribution by Survival', fontsize=14)

plt.subplot(1, 2, 2)
sns.boxplot(x='Survived', y='Fare', data=df, palette='viridis')
plt.title('Fare vs Survival', fontsize=14)
plt.xticks([0, 1], ['Not Survived', 'Survived'])

plt.tight_layout()
plt.show()

# Survival rate by Passenger Class
plt.figure(figsize=(10, 6))
sns.barplot(x='Pclass', y='Survived', data=df, estimator=np.mean, palette='viridis')
plt.title('Survival Rate by Passenger Class', fontsize=14)
plt.xlabel('Passenger Class', fontsize=12)
plt.ylabel('Survival Rate', fontsize=12)
plt.show()

# Survival rate by Sex
plt.figure(figsize=(10, 6))
sns.barplot(x='Sex', y='Survived', data=df, estimator=np.mean, palette='viridis')
plt.title('Survival Rate by Sex', fontsize=14)
plt.xlabel('Sex', fontsize=12)
plt.ylabel('Survival Rate', fontsize=12)
plt.show()

# Survival rate by Embarked
plt.figure(figsize=(10, 6))
sns.barplot(x='Embarked', y='Survived', data=df, estimator=np.mean, palette='viridis')
plt.title('Survival Rate by Port of Embarkation', fontsize=14)
plt.xlabel('Embarked', fontsize=12)
plt.ylabel('Survival Rate', fontsize=12)
plt.show()

# Create a correlation matrix for numerical variables
# Fill missing values for correlation calculation
df_corr = df.select_dtypes(include=['int64', 'float64']).copy()
df_corr.fillna(df_corr.mean(), inplace=True)

# Calculate correlation matrix
corr_matrix = df_corr.corr()

# Visualize correlation matrix
plt.figure(figsize=(12, 10))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
cmap = sns.diverging_palette(230, 20, as_cmap=True)
sns.heatmap(corr_matrix, mask=mask, cmap=cmap, vmax=1, vmin=-1, center=0,
            square=True, linewidths=.5, annot=True, fmt='.2f', cbar_kws={"shrink": .5})
plt.title('Correlation Matrix', fontsize=16)
plt.show()

# Pairplot for numerical variables
sns.pairplot(df[['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']].dropna(),
             hue='Survived', palette='viridis', diag_kind='kde')
plt.suptitle('Pairplot of Numerical Features', y=1.02, fontsize=16)
plt.show()

# Outlier Detection using Z-Score for Fare
z_scores = stats.zscore(df['Fare'].dropna())
outliers_z = np.abs(z_scores) > 3
print(f"Number of outliers detected by Z-score (|z| > 3): {outliers_z.sum()}")

# Visualize Z-score outliers
plt.figure(figsize=(12, 6))
plt.scatter(range(len(df['Fare'].dropna())), df['Fare'].dropna(), c=['red' if x else 'blue' for x in outliers_z])
plt.axhline(y=df['Fare'].mean() + 3*df['Fare'].std(), color='red', linestyle='-', alpha=0.3)
plt.axhline(y=df['Fare'].mean() - 3*df['Fare'].std(), color='red', linestyle='-', alpha=0.3)
plt.title('Z-score Outlier Detection for Fare', fontsize=14)
plt.xlabel('Index', fontsize=12)
plt.ylabel('Fare', fontsize=12)
plt.show()

# Outlier Detection using IQR method for Fare
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers_iqr = (df['Fare'] < lower_bound) | (df['Fare'] > upper_bound)
print(f"Number of outliers detected by IQR method: {outliers_iqr.sum()}")

# Visualize IQR outliers
plt.figure(figsize=(12, 6))
plt.scatter(range(len(df['Fare'])), df['Fare'], c=['red' if x else 'blue' for x in outliers_iqr])
plt.axhline(y=upper_bound, color='red', linestyle='-', alpha=0.3)
plt.axhline(y=lower_bound, color='red', linestyle='-', alpha=0.3)
plt.title('IQR Outlier Detection for Fare', fontsize=14)
plt.xlabel('Index', fontsize=12)
plt.ylabel('Fare', fontsize=12)
plt.show()

# Visualize relationship between age, fare, and survival
plt.figure(figsize=(12, 8))

# Filter the dataframe to use only rows where Age is not null
age_data = df.dropna(subset=['Age'])

scatter = plt.scatter(age_data['Age'],
                      age_data['Fare'].clip(upper=250),
                      c=age_data['Survived'],
                      cmap='viridis',
                      alpha=0.7,
                      s=age_data['Pclass']*50)

plt.colorbar(scatter, label='Survived')
plt.title('Relationship between Age, Fare, and Survival', fontsize=14)
plt.xlabel('Age', fontsize=12)
plt.ylabel('Fare (capped at 250)', fontsize=12)
plt.show()

# Feature Engineering Example - Age Groups
df['AgeGroup'] = pd.cut(df['Age'], bins=[0, 12, 18, 35, 60, 100],
                      labels=['Child', 'Teen', 'Young Adult', 'Adult', 'Elderly'])

# Survival rate by Age Group
plt.figure(figsize=(12, 6))
sns.barplot(x='AgeGroup', y='Survived', data=df, estimator=np.mean, palette='viridis')
plt.title('Survival Rate by Age Group', fontsize=14)
plt.xlabel('Age Group', fontsize=12)
plt.ylabel('Survival Rate', fontsize=12)
plt.show()

# Feature Engineering Example - Fare Categories
df['FareCategory'] = pd.qcut(df['Fare'], 4, labels=['Low', 'Medium', 'High', 'Very High'])

# Survival rate by Fare Category
plt.figure(figsize=(12, 6))
sns.barplot(x='FareCategory', y='Survived', data=df, estimator=np.mean, palette='viridis')
plt.title('Survival Rate by Fare Category', fontsize=14)
plt.xlabel('Fare Category', fontsize=12)
plt.ylabel('Survival Rate', fontsize=12)
plt.show()

# Family Size feature
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1  # +1 for the passenger themselves

# Survival rate by Family Size
plt.figure(figsize=(12, 6))
sns.barplot(x='FamilySize', y='Survived', data=df, estimator=np.mean, palette='viridis')
plt.title('Survival Rate by Family Size', fontsize=14)
plt.xlabel('Family Size', fontsize=12)
plt.ylabel('Survival Rate', fontsize=12)
plt.show()



"""# Excercise"""

# EDA CHALLENGE

# INSTRUCTIONS:
# 1. Create an analysis that explores whether a passenger's title (Mr, Mrs, Miss, etc.)
#    affected their survival chances on the Titanic.
# 2. Extract titles from the Name column
# 3. Group similar titles (optional)
# 4. Create appropriate visualizations to show the relationship between title and survival
# 5. Calculate and interpret relevant statistics
# 6. Draw conclusions based on your findings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns




df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)


title_mapping = {
    'Mlle': 'Miss', 'Ms': 'Miss', 'Mme': 'Mrs',
    'Lady': 'Rare', 'Countess': 'Rare', 'Capt': 'Rare', 'Col': 'Rare',
    'Don': 'Rare', 'Dr': 'Rare', 'Major': 'Rare', 'Rev': 'Rare',
    'Sir': 'Rare', 'Jonkheer': 'Rare', 'Dona': 'Rare'
}
df['Title'] = df['Title'].replace(title_mapping)


title_stats = df.groupby('Title')['Survived'].agg(['count', 'sum', 'mean']).reset_index()
title_stats.columns = ['Title', 'Total Passengers', 'Survived Count', 'Survival Rate']
title_stats['Survival Rate'] = title_stats['Survival Rate'].round(2)


print(title_stats.to_string(index=False))


plt.figure(figsize=(12, 5))


plt.subplot(1, 2, 1)
sns.countplot(data=df, x='Title', hue='Survived', palette='viridis',
              order=df['Title'].value_counts().index)
plt.title('Passenger Count by Title and Survival', fontsize=12)
plt.xlabel('Passenger Title')
plt.ylabel('Number of Passengers')


plt.subplot(1, 2, 2)
sns.barplot(data=df, x='Title', y='Survived', palette='viridis',
            estimator=np.mean, errorbar=None, order=df['Title'].value_counts().index)
plt.title('Survival Rate Percentage by Title', fontsize=12)
plt.xlabel('Passenger Title')
plt.ylabel('Survival Rate (0.0 to 1.0)')

plt.tight_layout()
plt.show()

#CONCLUSION
#Social Hierarchy:
 #Survival order was Mrs > Miss > Master > Rare > Mr
#.Women First (Mrs & Miss):
#Females had the highest survival rates (~70%+).
#Children Saved (Master):
# Young boys survived significantly more (~57%) than adult men.
 #Men Sacrificed (Mr):
 #Adult males had the lowest survival rate (~16%).

# Starter code to help you begin:
# Extract titles from passenger names
df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

# Preview the titles you've extracted
print(df['Title'].value_counts())

# Your code goes below:
# 1. Group similar titles if needed (e.g., group rare titles)
# ...

title_mapping = {
    'Mlle': 'Miss',
    'Ms': 'Miss',
    'Mme': 'Mrs',
    'Lady': 'Rare',
    'Countess': 'Rare',
    'Capt': 'Rare',
    'Col': 'Rare',
    'Don': 'Rare',
    'Dr': 'Rare',
    'Major': 'Rare',
    'Rev': 'Rare',
    'Sir': 'Rare',
    'Jonkheer': 'Rare',
    'Dona': 'Rare'
}

df['Title'] = df['Title'].replace(title_mapping)



print(df['Title'].value_counts())

# 2. Create visualizations showing relationship between title and survival
# ...

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(14, 6))


plt.subplot(1, 2, 1)
sns.countplot(data=df, x='Title', hue='Survived', palette='viridis',
              order=df['Title'].value_counts().index)
plt.title('Passenger Count by Title and Survival', fontsize=14)
plt.xlabel('Passenger Title', fontsize=12)
plt.ylabel('Number of Passengers', fontsize=12)


plt.subplot(1, 2, 2)
sns.barplot(data=df, x='Title', y='Survived', palette='viridis',
            estimator=np.mean, errorbar=None, order=df['Title'].value_counts().index)
plt.title('Survival Rate Percentage by Title', fontsize=14)
plt.xlabel('Passenger Title', fontsize=12)
plt.ylabel('Survival Rate (0.0 to 1.0)', fontsize=12)


plt.tight_layout()
plt.show()

# 3. Calculate relevant statistics (survival rate by title)
# ...

title_stats = df.groupby('Title')['Survived'].agg(['count', 'sum', 'mean']).reset_index()

title_stats.columns = ['Title', 'Total Passengers', 'Survived Count', 'Survival Rate']


title_stats['Survival Rate'] = (title_stats['Survival Rate'] * 100).round(2)


title_stats = title_stats.sort_values(by='Survival Rate', ascending=False)


print("=== STATISTICAL SUMMARY ===")
print(title_stats.to_string(index=False))

# 4. Draw conclusions - what patterns do you observe?
# ...

#1. Highest Survival Rate (Mrs & Miss):
   #- Married women (Mrs) followed by unmarried women/girls (Miss) have the highest survival rates.
   #- This directly reflects the historic "Women and children first" rescue protocol.

#2. Child Priority (Master):
  # - Young boys with the title 'Master' survived at a much higher rate (~57%) compared to adult men.
  # - This proves that children were given strong priority over regular male passengers during evacuation.

#3. Lowest Survival Rate (Mr):
  # - Adult males with the title 'Mr' represent the largest group of passengers but have the lowest survival rate.
  # - They were only allowed on lifeboats after women and children were secured.v

# BONUS:
# - Combine title with other features (like Pclass or Age) for deeper analysis
# - Create a visualization that shows this multi-factor relationship

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns


sns.stripplot(
    data=df,
    x="Title",
    y="Age",
    hue="Survived",
    palette="Set1",
    order=["Mr", "Miss", "Mrs", "Master", "Rare"],
)


plt.xlabel("Passenger Title")
plt.ylabel("Age")
plt.title("Survival Analysis by Title and Age")
plt.xticks(rotation=45)
plt.show()



stats = df.groupby(["Pclass", "Title"])["Survived"].mean() * 100
print(stats)











































