# -*- coding: utf-8 -*-
"""Week_3_Day_2_Assignment_task (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yxJQQ3axYB1R859Wsq2V-u11IjbCTU_z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.datasets import mnist
import cv2
from scipy import ndimage
import albumentations as A
import random
import warnings
warnings.filterwarnings('ignore')

# Load a sample dataset - we'll use both a tabular dataset and an image dataset
# For tabular data, let's use the Titanic dataset
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df.head()

# Basic Exploration
print(f"Dataset shape: {df.shape}")
print("\nMissing values per column:")
print(df.isnull().sum())

# Fill missing values
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df['Cabin'].fillna('Unknown', inplace=True)

"""# ----- FEATURE ENGINEERING FOR TABULAR DATA -----"""

# 1. Extract title from name
df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)
# Group rare titles
rare_titles = ['Lady', 'Countess','Capt', 'Col', 'Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona']
df['Title'] = df['Title'].replace(rare_titles, 'Rare')
df['Title'] = df['Title'].replace('Mlle', 'Miss')
df['Title'] = df['Title'].replace('Ms', 'Miss')
df['Title'] = df['Title'].replace('Mme', 'Mrs')

# 2. Create family size feature
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1  # +1 for the passenger themselves

# 3. Create is_alone feature
df['IsAlone'] = 0
df.loc[df['FamilySize'] == 1, 'IsAlone'] = 1

# 4. Create fare per person
df['FarePerPerson'] = df['Fare'] / df['FamilySize']

# 5. Bin age into categories
df['AgeBin'] = pd.cut(df['Age'], bins=[0, 12, 18, 65, 100], labels=['Child', 'Teenager', 'Adult', 'Elderly'])

# 6. Bin fare into categories
df['FareBin'] = pd.qcut(df['Fare'], 4, labels=['Low', 'Medium', 'High', 'Very High'])

# 7. Create deck from cabin
df['Deck'] = df['Cabin'].str[0]
df['Deck'] = df['Deck'].replace(['T', 'A', 'G'], 'Other')
df['Deck'] = df['Deck'].replace('Unknown', 'U')

# 8. Interaction features
df['Family_Survival'] = df['FamilySize'] * df['Survived']

# 9. Categorical encodings
# One-hot encoding for categorical features
categorical_features = ['Pclass', 'Sex', 'Embarked', 'Title', 'AgeBin', 'FareBin', 'Deck']
df_encoded = pd.get_dummies(df[categorical_features], drop_first=True)

# Combine with numerical features
numerical_features = ['Age', 'SibSp', 'Parch', 'Fare', 'FamilySize', 'IsAlone', 'FarePerPerson']
X = pd.concat([df[numerical_features], df_encoded], axis=1)
y = df['Survived']

# Feature scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Feature selection using SelectKBest
selector = SelectKBest(f_classif, k=15)
X_selected = selector.fit_transform(X_scaled, y)

# Display top features
feature_scores = pd.DataFrame({
    'Feature': X.columns,
    'Score': selector.scores_
})
top_features = feature_scores.sort_values('Score', ascending=False).head(15)
print("\nTop 15 features:")
print(top_features)

# Train a model with the engineered features
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.25, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)
print("\nModel accuracy with engineered features:", accuracy_score(y_test, y_pred))
print("\nClassification report:")
print(classification_report(y_test, y_pred))

"""# ----- ADVANCED FEATURE ENGINEERING -----"""

# 1. Polynomial features (example with a simple subset)
from sklearn.preprocessing import PolynomialFeatures

# Just using Age and Fare for demonstration
poly_features = PolynomialFeatures(degree=2, include_bias=False)
poly_data = poly_features.fit_transform(df[['Age', 'Fare']].fillna(0))

# Display polynomial feature names
feature_names = poly_features.get_feature_names_out(['Age', 'Fare'])
print("\nPolynomial features generated:")
print(feature_names)

# 2. PCA for dimensionality reduction
pca = PCA(n_components=10)
X_pca = pca.fit_transform(X_scaled)

# Plot explained variance ratio
plt.figure(figsize=(10, 6))
plt.bar(range(1, 11), pca.explained_variance_ratio_)
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance Ratio')
plt.title('Explained Variance by Components')
plt.tight_layout()
plt.show()

# Print cumulative explained variance
print("\nCumulative explained variance:")
print(np.cumsum(pca.explained_variance_ratio_))

"""# ----- DATA AUGMENTATION FOR IMAGES -----"""

# Load MNIST dataset for image augmentation examples
(X_train_img, y_train_img), (X_test_img, y_test_img) = mnist.load_data()

# Normalize the data
X_train_img = X_train_img / 255.0
X_test_img = X_test_img / 255.0

# Expand dimensions for Keras (add channel dimension)
X_train_img = X_train_img.reshape(-1, 28, 28, 1)
X_test_img = X_test_img.reshape(-1, 28, 28, 1)

# Display some original images
plt.figure(figsize=(10, 2))
for i in range(5):
    plt.subplot(1, 5, i+1)
    plt.imshow(X_train_img[i].reshape(28, 28), cmap='gray')
    plt.axis('off')
    plt.title(f"Label: {y_train_img[i]}")
plt.tight_layout()
plt.show()

# ----- 1. BASIC IMAGE AUGMENTATION WITH KERAS -----

datagen = ImageDataGenerator(
    rotation_range=10,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.1,
    shear_range=0.1,
  #3brightness_range=[0.5, 1.5],
    horizontal_flip=True,
    fill_mode='nearest'
)

# Visualize augmented images
augmented_images = []
for x_batch in datagen.flow(X_train_img[:5], batch_size=1, shuffle=False):
    augmented_images.append(x_batch[0])
    if len(augmented_images) >= 15:  # Generate 3 augmented versions of each of the 5 images
        break

# Display augmented images
plt.figure(figsize=(12, 8))
for i, img in enumerate(augmented_images):
    plt.subplot(3, 5, i+1)
    plt.imshow(img.reshape(28, 28), cmap='gray')
    plt.axis('off')
    if i < 5:
        plt.title(f"Original: {y_train_img[i]}")
plt.tight_layout()
plt.show()

# ----- 2. AUGMENTATION WITH TF.IMAGE -----
def augment_with_tf(image):
    # Convert to float32
    image = tf.cast(image, tf.float32)

    # Random rotation
    image = tf.image.rot90(image, k=tf.random.uniform(shape=[], minval=0, maxval=4, dtype=tf.int32))

    # Random brightness
    image = tf.image.random_brightness(image, max_delta=0.2)

    # Random contrast
    image = tf.image.random_contrast(image, lower=0.8, upper=1.2)

    # Ensure values are still between 0 and 1
    image = tf.clip_by_value(image, 0.0, 1.0)

    return image

# Apply tf.image augmentation to a few images
augmented_tf_images = []
for i in range(5):
    # Create 3 augmented versions of each image
    for _ in range(3):
        aug_img = augment_with_tf(X_train_img[i]).numpy()
        augmented_tf_images.append(aug_img)

# Display tf.image augmented images
plt.figure(figsize=(12, 8))
for i, img in enumerate(augmented_tf_images):
    plt.subplot(3, 5, i+1)
    plt.imshow(img.reshape(28, 28), cmap='gray')
    plt.axis('off')
plt.suptitle('tf.image Augmentation')
plt.tight_layout()
plt.show()

# ----- 3. AUGMENTATION WITH OPENCV -----

def opencv_augment(image):
    # Convert to 0-255 range and uint8 for OpenCV
    image = (image * 255).astype(np.uint8).reshape(28, 28)

    # Choose a random augmentation
    choice = np.random.choice(['rotate', 'blur', 'zoom', 'original'])

    if choice == 'rotate':
        # Random rotation
        angle = np.random.uniform(-15, 15)
        return ndimage.rotate(image, angle, reshape=False)

    elif choice == 'blur':
        # Add blur
        return cv2.GaussianBlur(image, (3, 3), 0)

    elif choice == 'zoom':
        # Random zoom
        zoom_factor = np.random.uniform(0.8, 1.2)
        height, width = image.shape

        # Compute new dimensions
        new_height = int(height * zoom_factor)
        new_width = int(width * zoom_factor)

        if zoom_factor < 1:  # Zoom out
            # Crop the image
            y_start = (height - new_height) // 2
            x_start = (width - new_width) // 2
            cropped = image[y_start:y_start+new_height, x_start:x_start+new_width]
            # Resize back to original size
            return cv2.resize(cropped, (width, height))
        else:  # Zoom in
            # Resize
            resized = cv2.resize(image, (new_width, new_height))
            # Crop to original size
            y_start = (new_height - height) // 2
            x_start = (new_width - width) // 2
            return resized[y_start:y_start+height, x_start:x_start+width]

    else:
        # Return original
        return image

# Apply OpenCV augmentation
opencv_augmented = []
for i in range(5):
    # Create 3 augmented versions of each image
    for _ in range(3):
        aug_img = opencv_augment(X_train_img[i])
        # Normalize back to 0-1
        aug_img = aug_img.astype(np.float32) / 255.0
        opencv_augmented.append(aug_img)

# Display OpenCV augmented images
plt.figure(figsize=(12, 8))
for i, img in enumerate(opencv_augmented):
    plt.subplot(3, 5, i+1)
    plt.imshow(img, cmap='gray')
    plt.axis('off')
plt.suptitle('OpenCV Augmentation')
plt.tight_layout()
plt.show()

# ----- 4. AUGMENTATION WITH ALBUMENTATIONS -----

def apply_albumentation(image):
    # Convert to 0-255 range and uint8 for Albumentations
    image = (image * 255).astype(np.uint8).reshape(28, 28)

    # Define transformation pipeline
    transform = A.Compose([
        A.OneOf([
            A.RandomBrightnessContrast(p=0.8),
            A.RandomGamma(p=0.8),
        ], p=0.5),
        A.OneOf([
            A.ElasticTransform(alpha=1, sigma=50, alpha_affine=50, p=0.5),
            A.GridDistortion(p=0.5),
            A.OpticalDistortion(distort_limit=2, shift_limit=0.5, p=0.5),
        ], p=0.5),
    ])

    # Apply transformation
    augmented = transform(image=image)['image']

    # Normalize back to 0-1
    return augmented.astype(np.float32) / 255.0

# Apply Albumentations
albu_augmented = []
for i in range(5):
    # Create 3 augmented versions of each image
    for _ in range(3):
        aug_img = apply_albumentation(X_train_img[i])
        albu_augmented.append(aug_img)

# Display Albumentations augmented images
plt.figure(figsize=(12, 8))
for i, img in enumerate(albu_augmented):
    plt.subplot(3, 5, i+1)
    plt.imshow(img, cmap='gray')
    plt.axis('off')
plt.suptitle('Albumentations Augmentation')
plt.tight_layout()
plt.show()

# ----- 5. TEXT DATA AUGMENTATION -----

# Sample texts
texts = [
    "This is a great product, I love it!",
    "The service was terrible and I'm disappointed.",
    "I'm not sure how I feel about this experience.",
    "The food was delicious and the staff was friendly.",
    "This movie is boring and too long."
]

# Simple text augmentation techniques
def swap_words(text):
    words = text.split()
    if len(words) <= 1:
        return text

    idx1, idx2 = sorted(random.sample(range(len(words)), 2))
    words[idx1], words[idx2] = words[idx2], words[idx1]
    return ' '.join(words)

def delete_random_word(text):
    words = text.split()
    if len(words) <= 1:
        return text

    idx = random.randrange(len(words))
    return ' '.join(words[:idx] + words[idx+1:])

def insert_random_word(text, word_list=["really", "very", "somewhat", "quite", "extremely"]):
    words = text.split()
    if not words:
        return text

    idx = random.randrange(len(words))
    word_to_insert = random.choice(word_list)
    return ' '.join(words[:idx] + [word_to_insert] + words[idx:])

# Apply text augmentation
augmented_texts = []
for text in texts:
    augmented_texts.append(("Original", text))
    augmented_texts.append(("Word Swap", swap_words(text)))
    augmented_texts.append(("Word Deletion", delete_random_word(text)))
    augmented_texts.append(("Word Insertion", insert_random_word(text)))

# Display original and augmented texts
print("\nText Data Augmentation Examples:")
for aug_type, text in augmented_texts:
    print(f"{aug_type}: {text}")

# ----- 6. ADVANCED APPLICATION: AUGMENT TO BALANCE CLASSES -----

# Check distribution of classes in MNIST
unique, counts = np.unique(y_train_img, return_counts=True)
class_distribution = dict(zip(unique, counts))

plt.figure(figsize=(10, 6))
plt.bar(class_distribution.keys(), class_distribution.values())
plt.xlabel('Digit')
plt.ylabel('Count')
plt.title('MNIST Training Set Class Distribution')
plt.show()

def augment_minority_class(X, y, target_class, num_samples):
    # Find samples of the target class
    class_indices = np.where(y == target_class)[0]
    X_class = X[class_indices]

    # If we already have enough samples, no need to augment
    if len(X_class) >= num_samples:
        return X, y

    # Number of augmentations needed
    num_augmentations = num_samples - len(X_class)

    # Create augmentation generator
    datagen = ImageDataGenerator(
        rotation_range=15,
        width_shift_range=0.2,
        height_shift_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
        fill_mode='nearest'
    )

    # Generate augmented images
    augmented_images = []
    augmented_labels = []

    for x_batch in datagen.flow(X_class, batch_size=1, shuffle=True):
        augmented_images.append(x_batch[0])
        augmented_labels.append(target_class)
        if len(augmented_images) >= num_augmentations:
            break

    # Convert to numpy arrays
    augmented_images = np.array(augmented_images)
    augmented_labels = np.array(augmented_labels)

    # Combine original and augmented data
    X_balanced = np.vstack([X, augmented_images])
    y_balanced = np.hstack([y, augmented_labels])

    return X_balanced, y_balanced

# Demonstrate balancing a subset of MNIST
# For demonstration, let's use just 100 samples per class initially
X_sample = []
y_sample = []

for digit in range(10):
    indices = np.where(y_train_img == digit)[0][:100]  # Take 100 samples of each digit
    X_sample.extend(X_train_img[indices])
    y_sample.extend(y_train_img[indices])

X_sample = np.array(X_sample)
y_sample = np.array(y_sample)

# Print initial distribution
unique, counts = np.unique(y_sample, return_counts=True)
print("\nInitial distribution:")
print(dict(zip(unique, counts)))

# Let's artificially create an imbalance by removing some '8' samples
eight_indices = np.where(y_sample == 8)[0]
remove_indices = eight_indices[:80]  # Remove 80 samples of digit 8
mask = np.ones(len(y_sample), dtype=bool)
mask[remove_indices] = False

X_imbalanced = X_sample[mask]
y_imbalanced = y_sample[mask]

# Print imbalanced distribution
unique, counts = np.unique(y_imbalanced, return_counts=True)
print("\nImbalanced distribution:")
print(dict(zip(unique, counts)))

# Balance the dataset using augmentation
X_balanced, y_balanced = augment_minority_class(X_imbalanced, y_imbalanced, 8, 100)

# Print balanced distribution
unique, counts = np.unique(y_balanced, return_counts=True)
print("\nBalanced distribution after augmentation:")
print(dict(zip(unique, counts)))

# ----- 7. DEMONSTRATING THE EFFECT OF AUGMENTATION ON MODEL PERFORMANCE -----

# Create a simple CNN model for MNIST
def create_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Train model on imbalanced data
model_imbalanced = create_model()
history_imbalanced = model_imbalanced.fit(X_imbalanced, y_imbalanced, epochs=5,
                                           validation_split=0.2, verbose=0)

# Train model on balanced data
model_balanced = create_model()
history_balanced = model_balanced.fit(X_balanced, y_balanced, epochs=5,
                                       validation_split=0.2, verbose=0)

# Compare performance
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history_imbalanced.history['accuracy'], label='Imbalanced - Train')
plt.plot(history_imbalanced.history['val_accuracy'], label='Imbalanced - Validation')
plt.plot(history_balanced.history['accuracy'], label='Balanced - Train')
plt.plot(history_balanced.history['val_accuracy'], label='Balanced - Validation')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_imbalanced.history['loss'], label='Imbalanced - Train')
plt.plot(history_imbalanced.history['val_loss'], label='Imbalanced - Validation')
plt.plot(history_balanced.history['loss'], label='Balanced - Train')
plt.plot(history_balanced.history['val_loss'], label='Balanced - Validation')
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend()

plt.tight_layout()
plt.show()

"""# Excercise"""

# 1. Setup and Data Loading

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# TODO: Load the Titanic dataset into `df` using pd.read_csv
# Hint: URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
#df = None  # TODO


# TODO: Load the Titanic dataset into `df` using pd.read_csv
# Hint: URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(URL) # TODO

# TODO: Display first 5 rows and the dataset shape
print("First 5 rows:")
print(df.head())
print("\nDataset Shape:", df.shape)



# TODO: Display first 5 rows and the dataset shape
# TODO: Print missing value counts per column
print("\nMissing Values per Column")
print(df.isnull().sum())

# TODO: Fill missing 'Age' with its median
# TODO: Fill missing 'Embarked' with its mode
# TODO: Replace missing 'Cabin' entries with 'Unknown'

# 2. Missing Value Imputation

# TODO: Fill missing 'Age' with its median
df['Age'] = df['Age'].fillna(df['Age'].median())

# TODO: Fill missing 'Embarked' with its mode
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# TODO: Replace missing 'Cabin' entries with 'Unknown'
df['Cabin'] = df['Cabin'].fillna('Unknown')

# Check karo sab theek hua ya nahi
print("Missing Values after Imputation:")
print(df.isnull().sum())

# 3. Feature Engineering

# 3.1 Extract Title from Name
# TODO: Create df['Title'] by extracting the substring before '.' in Name

# 3.2 Group rare titles into 'Rare' and standardize variants
rare_titles = [...]
# TODO: Replace rare and variant titles accordingly

# 3.3 Family Size and IsAlone
# TODO: df['FamilySize'] = SibSp + Parch + 1
# TODO: df['IsAlone'] = 1 where FamilySize == 1, else 0

# 3.4 Fare Per Person
# TODO: df['FarePerPerson'] = Fare / FamilySize

# 3.5 Age and Fare Binning
# TODO: Create AgeBin categories: Child (0–12), Teenager (13–18), Adult (19–65), Elderly (>65)
# TODO: Create FareBin quantiles: Low, Medium, High, Very High

# 3.6 Deck from Cabin
# TODO: df['Deck'] = first letter of Cabin; replace 'Unknown'→'U' and rare letters→'Other'

# 3. Feature Engineering

# 3.1 Extract Title from Name
# TODO: Create df['Title'] by extracting the substring before '.' in Name
df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

# 3.2 Group rare titles into 'Rare' and standardize variants
rare_titles = ['Lady', 'Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona']
# TODO: Replace rare and variant titles accordingly
df['Title'] = df['Title'].replace(['Mlle','Mme'], ['Miss','Mrs'])
df['Title'] = df['Title'].replace(rare_titles, 'Rare')

# 3.3 Family Size and IsAlone
# TODO: df['FamilySize'] = SibSp + Parch + 1
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
# TODO: df['IsAlone'] = 1 where FamilySize == 1, else 0
df['IsAlone'] = np.where(df['FamilySize'] == 1, 1, 0)

# 3.4 Fare Per Person
# TODO: df['FarePerPerson'] = Fare / FamilySize
df['FarePerPerson'] = df['Fare'] / df['FamilySize']

# 3.5 Age and Fare Binning
# TODO: Create AgeBin categories: Child (0-12), Teenager (13-18), Adult (19-65), Elderly (>65)
bins_age = [0, 12, 18, 65, 100]
labels_age = ['Child', 'Teenager', 'Adult', 'Elderly']
df['AgeBin'] = pd.cut(df['Age'], bins=bins_age, labels=labels_age)

# TODO: Create FareBin quantiles: Low, Medium, High, Very High
df['FareBin'] = pd.qcut(df['Fare'], 4, labels=['Low', 'Medium', 'High', 'Very High'])

# 3.6 Deck from Cabin
# TODO: df['Deck'] = first letter of Cabin; replace 'Unknown'->'U' and rare letters->'Other'
df['Deck'] = df['Cabin'].str[0]
df['Deck'] = df['Deck'].replace('U', 'Unknown') # pehle wale step se Unknown aaya tha
common_decks = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
df['Deck'] = df['Deck'].apply(lambda x: x if x in common_decks else 'Other')

print("New Features Created. Head:")
print(df[['Name','Title','FamilySize','IsAlone','FarePerPerson','AgeBin','FareBin','Deck']].head())

# 4. Encoding and Scaling

# 4.1 One‑hot encode selected categorical columns using pd.get_dummies :contentReference[oaicite:11]{index=11}
categorical = ['Pclass','Sex','Embarked','Title','AgeBin','FareBin','Deck']
# TODO: df_encoded = pd.get_dummies(df[categorical], drop_first=True)

# 4.2 Combine with numerical features
numerical = ['Age','SibSp','Parch','Fare','FamilySize','IsAlone','FarePerPerson']
# TODO: X = pd.concat([...], axis=1)
# TODO: y = df['Survived']

# 4.3 Feature scaling: fit three different scalers and transform X
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
# TODO: scaler_std = StandardScaler()       # :contentReference[oaicite:12]{index=12}
# TODO: scaler_mm  = MinMaxScaler()
# TODO: scaler_rbv = RobustScaler()
# TODO: X_std = scaler_std.fit_transform(X)
# TODO: X_mm  = scaler_mm.fit_transform(X)
# TODO: X_rb  = scaler_rbv.fit_transform(X)

# 4. Encoding and Scaling

# 4.1 One-hot encode selected categorical columns using pd.get_dummies
categorical = ['Pclass','Sex','Embarked','Title','AgeBin','FareBin','Deck']
# TODO: df_encoded = pd.get_dummies(df[categorical], drop_first=True)
df_encoded = pd.get_dummies(df[categorical], drop_first=True)

print("Encoded shape:", df_encoded.shape)
print(df_encoded.head())

# 4.2 Combine with numerical features
numerical = ['Age','SibSp','Parch','Fare','FamilySize','IsAlone','FarePerPerson']
# TODO: X = pd.concat([df_encoded, df[numerical]], axis=1)
X = pd.concat([df_encoded, df[numerical]], axis=1)
# TODO: y = df['Survived']
y = df['Survived']

print("\nFinal X shape:", X.shape)
print("y shape:", y.shape)

# 4.3 Feature scaling: fit three different scalers and transform X
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
# TODO: scaler_std = StandardScaler()
scaler_std = StandardScaler()
# TODO: scaler_mm = MinMaxScaler()
scaler_mm = MinMaxScaler()
# TODO: scaler_rbv = RobustScaler()
scaler_rbv = RobustScaler()

# TODO: X_std = scaler_std.fit_transform(X)
X_std = scaler_std.fit_transform(X)
# TODO: X_mm = scaler_mm.fit_transform(X)
X_mm = scaler_mm.fit_transform(X)
# TODO: X_rb = scaler_rbv.fit_transform(X)
X_rb = scaler_rbv.fit_transform(X)

print("\nScaling Done!")
print("X_std shape:", X_std.shape)
print("X_mm shape:", X_mm.shape)
print("X_rb shape:", X_rb.shape)

# 5. Feature Selection & Modeling

from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# TODO: Use SelectKBest(f_classif, k=15) to pick top features :contentReference[oaicite:13]{index=13}
selector = None  # TODO
# TODO: X_sel = selector.fit_transform(X_std, y)
# TODO: top_feats = pd.DataFrame({'Feature': X.columns, 'Score': selector.scores_}).nlargest(15,'Score')

# TODO: Split into train/test (25% test), train RandomForestClassifier, and print:
#       - Accuracy
#       - Classification report

# 5. Feature Selection & Modeling

from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# TODO: Use SelectKBest(f_classif, k=15) to pick top features
selector = SelectKBest(score_func=f_classif, k=15) # TODO

# TODO: X_sel = selector.fit_transform(X_std, y)
X_sel = selector.fit_transform(X_std, y)

# TODO: top_feats = pd.DataFrame({'Feature': X.columns, 'Score': selector.scores_}).nlargest(15,'Score')
top_feats = pd.DataFrame({'Feature': X.columns, 'Score': selector.scores_}).nlargest(15,'Score')

print("Top 15 Features by f_classif score:")
print(top_feats)

# TODO: Split into train/test (25% test), train RandomForestClassifier, and print:
#       - Accuracy
#       - Classification report
X_train, X_test, y_train, y_test = train_test_split(X_sel, y, test_size=0.25, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\n--- Model Performance ---")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# 6. Advanced Feature Engineering

# 6.1 Polynomial Features using sklearn.preprocessing.PolynomialFeatures :contentReference[oaicite:14]{index=14}
from sklearn.preprocessing import PolynomialFeatures



from sklearn.decomposition import PCA
# TODO: pca = PCA(n_components=10)
# TODO: X_pca = pca.fit_transform(X_std)
# TODO: Plot explained variance ratio bar chart
# TODO: Print cumulative variance (np.cumsum)

# 6. Advanced Feature Engineering

# 6.1 Polynomial Features using sklearn.preprocessing.PolynomialFeatures
from sklearn.preprocessing import PolynomialFeatures
# TODO: poly = PolynomialFeatures(degree=2, include_bias=False)
poly = PolynomialFeatures(degree=2, include_bias=False)
# TODO: poly_data = poly.fit_transform(df[['Age','Fare']].fillna(0))
poly_data = poly.fit_transform(df[['Age','Fare']].fillna(0))
# TODO: print(poly.get_feature_names_out(['Age','Fare']))
print("Polynomial Features for Age and Fare:")
print(poly.get_feature_names_out(['Age','Fare']))
print("\nPolynomial Data Shape:", poly_data.shape)


# 6.2 PCA for dimensionality reduction
from sklearn.decomposition import PCA
# TODO: pca = PCA(n_components=10)
pca = PCA(n_components=10)
# TODO: X_pca = pca.fit_transform(X_std)
X_pca = pca.fit_transform(X_std)

print("\nPCA Data Shape:", X_pca.shape)

# TODO: Plot explained variance ratio bar chart
plt.figure(figsize=(8,5))
plt.bar(range(1, 11), pca.explained_variance_ratio_, alpha=0.7, color='skyblue')
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance Ratio')
plt.title('PCA Explained Variance Ratio')
plt.xticks(range(1, 11))
plt.grid(axis='y')
plt.show()

# TODO: Print cumulative variance (np.cumsum)
cumulative_variance = np.cumsum(pca.explained_variance_ratio_)
print("\nCumulative Explained Variance:")
for i, var in enumerate(cumulative_variance, 1):
    print(f"PC{i}: {var:.4f}")

# 7. Image Data Augmentation

from tensorflow.keras.preprocessing.image import ImageDataGenerator  # :contentReference[oaicite:16]{index=16}
from tensorflow.keras.datasets import mnist

# TODO: Load MNIST, normalize, and reshape to (28,28,1)
# TODO: Display 5 sample images with true labels

# 7.1 Keras ImageDataGenerator
datagen = ImageDataGenerator(rotation_range=10,
                             width_shift_range=0.1,
                             height_shift_range=0.1,
                             zoom_range=0.1,
                             shear_range=0.1,
                             brightness_range=[0.5,1.5],
                             horizontal_flip=True,
                             fill_mode='nearest')
# TODO: Generate and plot 3 augmentations per sample for first 5 images

# 7.2 tf.image augmentations :contentReference[oaicite:17]{index=17}
import tensorflow as tf
# TODO: Write a function using tf.image.rot90, tf.image.random_brightness, tf.image.random_contrast

# 7.3 OpenCV augmentations :contentReference[oaicite:18]{index=18}
import cv2
from scipy import ndimage
import numpy as np
# TODO: Write opencv_augment() that randomly applies rotate, blur, or zoom

# 7.4 Albumentations pipeline :contentReference[oaicite:19]{index=19}
import albumentations as A
# TODO: Define A.Compose with RandomBrightnessContrast, ElasticTransform, GridDistortion, OpticalDistortion

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.datasets import mnist

# 1. Load MNIST, normalize, and reshape to (28,28,1)
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.astype('float32') / 255.0
x_train = np.expand_dims(x_train, axis=-1)

# 2. Display 5 sample images with true labels
plt.figure(figsize=(10, 2))
for i in range(5):
    plt.subplot(1, 5, i+1)
    plt.imshow(x_train[i].squeeze(), cmap='gray')
    plt.title(f"Label: {y_train[i]}")
    plt.axis('off')
plt.tight_layout()
plt.show()

datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.1,
    shear_range=0.1,
    fill_mode='nearest'
)


plt.figure(figsize=(12, 10))

for i in range(5):
    img = x_train[i]
    img_batch = np.expand_dims(img, 0) # batch dimension (1, 28, 28, 1)
    aug_iter = datagen.flow(img_batch, batch_size=1)

    # Column 1: Original Image
    plt.subplot(5, 4, i * 4 + 1)
    plt.imshow(img.squeeze(), cmap='gray')
    plt.title(f"Original: {y_train[i]}", fontsize=10)
    plt.axis('off')

    # Columns 2, 3, 4: Augmented Images
    for j in range(3):
        aug_img = next(aug_iter)[0]
        plt.subplot(5, 4, i * 4 + j + 2)
        plt.imshow(aug_img.squeeze(), cmap='gray')
        plt.title("Augmented", fontsize=10)
        plt.axis('off')

# 🛠️ FIX: Grid borders aur text headings ko safe doori par alignment dena
plt.tight_layout()
plt.show()

# 8. Text Data Augmentation

import random  # :contentReference[oaicite:20]{index=20}

# Sample sentences provided
texts = [...]

# TODO: Implement swap_words(text), delete_random_word(text), insert_random_word(text)
# TODO: For each original text, print the 3 augmented variants

# 8. Text Data Augmentation

import random

# Sample sentences provided
texts = [
    "The Titanic was a luxury liner that sank in 1912.",
    "Machine learning is used for data analysis.",
    "Data augmentation helps improve model performance."
]





###33 Implement swap_words(text), delete_random_word(text), insert_random_word(text)
def swap_words(text):
    words = text.split()
    if len(words) < 2:
        return text
    idx1, idx2 = random.sample(range(len(words)), 2)
    words[idx1], words[idx2] = words[idx2], words[idx1]
    return ' '.join(words)

def delete_random_word(text):
    words = text.split()
    if len(words) < 2:
        return text
    idx = random.randint(0, len(words)-1)
    words.pop(idx)
    return ' '.join(words)

def insert_random_word(text):
    words = text.split()
    vocab = ["data", "model", "AI", "feature", "result", "new", "very", "good"] # small vocab
    idx = random.randint(0, len(words))
    random_word = random.choice(vocab)
    words.insert(idx, random_word)
    return ' '.join(words)

# TODO: For each original text, print the 3 augmented variants
print("--- Text Augmentation Results ---")
for i, text in enumerate(texts):
    print(f"\nOriginal {i+1}: {text}")
    print(f"1. Swap Words: {swap_words(text)}")
    print(f"2. Delete Word: {delete_random_word(text)}")
    print(f"3. Insert Word: {insert_random_word(text)}")# 8. Text Data Augmentation

# 9. Class Balancing via Augmentation

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# TODO: Compute class distribution of y_train_img
# TODO: Write augment_minority_class(X, y, target_class, num_samples) that:
#         – Finds indices for target_class
#         – Uses ImageDataGenerator.flow to generate until desired count
#         – Returns augmented X_balanced, y_balanced

# 9. Class Balancing via Augmentation

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
from collections import Counter

# Assume x_train, y_train_img already loaded. Example with MNIST
from tensorflow.keras.datasets import mnist
(x_train, y_train_img), _ = mnist.load_data()
x_train = x_train.astype('float32') / 255.0
x_train = np.expand_dims(x_train, axis=-1) # shape (60000, 28, 28, 1)

# TODO: Compute class distribution of y_train_img
def print_distribution(y, title):
    counts = Counter(y)
    print(f"\n{title}")
    for cls, count in sorted(counts.items()):
        print(f"Class {cls}: {count} samples")

print_distribution(y_train_img, "Original Class Distribution")

# Make an imbalanced dataset for demo: keep only 500 samples of class 0
imbalanced_idx = np.concatenate([np.where(y_train_img==0)[0][:500],
                                 np.where(y_train_img!=0)[0]])
X_imb = x_train[imbalanced_idx]
y_imb = y_train_img[imbalanced_idx]
print_distribution(y_imb, "Imbalanced Class Distribution")


def augment_minority_class(X, y, target_class, num_samples):
    # 1. Find indices for target_class
    idx = np.where(y == target_class)[0]
    X_minority = X[idx]
    y_minority = y[idx]

    # 2. ImageDataGenerator setup
    datagen = ImageDataGenerator(
        rotation_range=15,
        width_shift_range=0.1,
        height_shift_range=0.1,
        zoom_range=0.1,
        shear_range=0.1,
        fill_mode='nearest'
    )

    # 3. Generate new samples
    aug_X, aug_y = [], []
    generator = datagen.flow(X_minority, y_minority, batch_size=32, shuffle=True)

    while len(aug_X) < num_samples:
        X_batch, y_batch = next(generator)
        aug_X.append(X_batch)
        aug_y.append(y_batch)

    aug_X = np.concatenate(aug_X, axis=0)[:num_samples]
    aug_y = np.concatenate(aug_y, axis=0)[:num_samples]

    # 4. Combine with original data
    X_balanced = np.concatenate([X, aug_X], axis=0)
    y_balanced = np.concatenate([y, aug_y], axis=0)

    return X_balanced, y_balanced

# Example: Balance class 0 to 5000 samples
target = 0
needed = 5000 - len(np.where(y_imb==target)[0])
X_bal, y_bal = augment_minority_class(X_imb, y_imb, target_class=target, num_samples=needed)

print_distribution(y_bal, "Balanced Class Distribution After Augmentation")
print(f"\nNew X shape: {X_bal.shape}, New y shape: {y_bal.shape}")

# 10. Effect of Augmentation on Model Performance

import tensorflow as tf

# TODO: Define create_model() as simple CNN
# TODO: Train on imbalanced subset (e.g. first 100 per class minus some for class '8')
# TODO: Train on balanced data after augmentation
# TODO: Plot training/validation accuracy and loss side by side

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import mnist
from tensorflow.keras.preprocessing.image import ImageDataGenerator


(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

x_train = np.expand_dims(x_train, axis=-1)
x_test = np.expand_dims(x_test, axis=-1)

# Imbalanced Data Setup
X_imb_list, y_imb_list = [], []
for c in range(10):
    idx = np.where(y_train == c)[0]
    count = 10 if c == 8 else 100
    X_imb_list.append(x_train[idx[:count]])
    y_imb_list.append(y_train[idx[:count]])

X_imb = np.vstack(X_imb_list)
y_imb = np.concatenate(y_imb_list)

# Augmented Data Setup
datagen = ImageDataGenerator(rotation_range=15, width_shift_range=0.1, height_shift_range=0.1, fill_mode='nearest')
X_bal, y_bal = X_imb.copy(), y_imb.copy()

idx_8 = np.where(y_imb == 8)[0]
samples_needed = 90
aug_images = []
for _ in range(samples_needed):
    random_img = X_imb[np.random.choice(idx_8)]
    aug_img = datagen.random_transform(random_img)
    aug_images.append(aug_img)

if len(aug_images) > 0:
    X_bal = np.concatenate([X_bal, np.array(aug_images)])
    y_bal = np.concatenate([y_bal, np.full(samples_needed, 8)])


def create_model():
    model = models.Sequential([
        layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(64, (3,3), activation='relu'),
        layers.MaxPooling2D((2,2)),
        layers.Flatten(),
        layers.Dense(64, activation='relu'),
        layers.Dense(10, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

print("\n--- Training on IMBALANCED Data ---")
model_imb = create_model()
hist_imb = model_imb.fit(X_imb, y_imb, epochs=5, batch_size=32, validation_split=0.2, verbose=1)

print("\n--- Training on BALANCED Data (Augmented) ---")
model_bal = create_model()
hist_bal = model_bal.fit(X_bal, y_bal, epochs=5, batch_size=32, validation_split=0.2, verbose=1)


plt.figure(figsize=(12, 4))

# Graph 1: Accuracy Curve
plt.subplot(1, 2, 1)
plt.plot(hist_imb.history['accuracy'], 'r-',  label='Imb Train')
plt.plot(hist_imb.history['val_accuracy'], 'r--', label='Imb Val')
plt.plot(hist_bal.history['accuracy'], 'g-',  label='Bal Train')
plt.plot(hist_bal.history['val_accuracy'], 'g--', label='Bal Val')
plt.title('Accuracy Comparison', fontweight='bold')
plt.xlabel('Epoch'); plt.ylabel('Accuracy'); plt.legend(); plt.grid(True, alpha=0.3)


plt.subplot(1, 2, 2)
plt.plot(hist_imb.history['loss'], 'r-',  label='Imb Train')
plt.plot(hist_imb.history['val_loss'], 'r--', label='Imb Val')
plt.plot(hist_bal.history['loss'], 'g-',  label='Bal Train')
plt.plot(hist_bal.history['val_loss'], 'g--', label='Bal Val')
plt.title('Loss Comparison', fontweight='bold')
plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.legend(); plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()


results_imb = model_imb.evaluate(x_test, y_test, verbose=0)
results_bal = model_bal.evaluate(x_test, y_test, verbose=0)


acc_imb = results_imb[1]
acc_bal = results_bal[1]

print("\n--- FINAL TEST EVALUATION ---")
print(f"Test Accuracy without Augmentation: {acc_imb:.4f}")
print(f"Test Accuracy with Augmentation:    {acc_bal:.4f}")

"""**Experiment: feel free to tweak parameters (e.g., k in SelectKBest, PCA components, augmentation ranges) to see their impact.**"""